<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Renan Monteiro Barbosa">
<meta name="description" content="Trying to replicate the Stroke_results_1019_2025_latest">

<title>Reproducing Steve’s Code - Stroke_results_1019_2025_latest – IDC-6940 - Capstone Project Fall-2025</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-2fef5ea3f8957b3e4ecc936fc74692ca.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-1773efb2f7ab98e3656670b7729847ad.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-cef3429e03e90a75e86301dc8df8cee2.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-1773efb2f7ab98e3656670b7729847ad.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">IDC-6940 - Capstone Project Fall-2025</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../report.html"> 
<span class="menu-text">Report</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blog.html"> 
<span class="menu-text">Literature Review</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../people/index.html"> 
<span class="menu-text">About Us</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
    <a href="https://github.com/renanmb/IDC-6940---Capstone-Project-Fall-2025" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#setup-and-data-loading" id="toc-setup-and-data-loading" class="nav-link active" data-scroll-target="#setup-and-data-loading">1. Setup and Data Loading</a>
  <ul class="collapse">
  <li><a href="#load-libraries" id="toc-load-libraries" class="nav-link" data-scroll-target="#load-libraries">1.1 Load Libraries</a></li>
  <li><a href="#load-data" id="toc-load-data" class="nav-link" data-scroll-target="#load-data">1.2 Load Data</a></li>
  <li><a href="#prepare-dataset" id="toc-prepare-dataset" class="nav-link" data-scroll-target="#prepare-dataset">1.3 Prepare Dataset</a></li>
  </ul></li>
  <li><a href="#apply-logistic-regression" id="toc-apply-logistic-regression" class="nav-link" data-scroll-target="#apply-logistic-regression">2. Apply Logistic Regression</a></li>
  <li><a href="#testing-logistic-regression-model-assumptions" id="toc-testing-logistic-regression-model-assumptions" class="nav-link" data-scroll-target="#testing-logistic-regression-model-assumptions">3. Testing logistic Regression Model Assumptions</a>
  <ul class="collapse">
  <li><a href="#testing-assumption-1" id="toc-testing-assumption-1" class="nav-link" data-scroll-target="#testing-assumption-1">3.1 Testing Assumption 1</a></li>
  <li><a href="#testing-assumption-2" id="toc-testing-assumption-2" class="nav-link" data-scroll-target="#testing-assumption-2">3.2 Testing Assumption 2</a></li>
  <li><a href="#testing-assumption-3" id="toc-testing-assumption-3" class="nav-link" data-scroll-target="#testing-assumption-3">3.3 Testing Assumption 3</a></li>
  </ul></li>
  <li><a href="#error---object-not-found" id="toc-error---object-not-found" class="nav-link" data-scroll-target="#error---object-not-found">Error - Object not found</a></li>
  <li><a href="#testing-assumption-4" id="toc-testing-assumption-4" class="nav-link" data-scroll-target="#testing-assumption-4">3.4 Testing Assumption 4</a></li>
  <li><a href="#analysis-of-the-model" id="toc-analysis-of-the-model" class="nav-link" data-scroll-target="#analysis-of-the-model">4 Analysis of the Model</a>
  <ul class="collapse">
  <li><a href="#use-hosmer-lemesho-and-naglekerke-r" id="toc-use-hosmer-lemesho-and-naglekerke-r" class="nav-link" data-scroll-target="#use-hosmer-lemesho-and-naglekerke-r">4.1 Use Hosmer-lemesho and Naglekerke R</a></li>
  <li><a href="#predictive-capability" id="toc-predictive-capability" class="nav-link" data-scroll-target="#predictive-capability">4.2 Predictive Capability</a></li>
  </ul></li>
  <li><a href="#original-code" id="toc-original-code" class="nav-link" data-scroll-target="#original-code">Original Code</a>
  <ul class="collapse">
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Reproducing Steve’s Code - Stroke_results_1019_2025_latest</h1>
  <div class="quarto-categories">
    <div class="quarto-category">coding</div>
    <div class="quarto-category">week 8</div>
    <div class="quarto-category">renan</div>
  </div>
  </div>

<div>
  <div class="description">
    Trying to replicate the Stroke_results_1019_2025_latest
  </div>
</div>

<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author"><a href="https://github.com/renanmb">Renan Monteiro Barbosa</a> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Master of Data Science Program @ The University of West Florida (UWF)
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  


</header>


<p>On this document I try to replicate Steve code: <strong>Stroke_Results_1019_2025_latest_440PM_SW_For_Group.R</strong></p>
<section id="setup-and-data-loading" class="level2">
<h2 class="anchored" data-anchor-id="setup-and-data-loading">1. Setup and Data Loading</h2>
<p>First we need to install all packages, system dependencies and solve conflicts to produce a new renv.lock file.</p>
<section id="load-libraries" class="level3">
<h3 class="anchored" data-anchor-id="load-libraries">1.1 Load Libraries</h3>
<p>Install packages if necessary:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run this once to install all the necessary packages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("dplyr")</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("car")</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("ResourceSelection")</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("caret")</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("rcompanion")</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("pROC")</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("cvAUC")</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Load Libraries:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># For data manipulation and visualization</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co"># For data preprocessing and modeling</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mice)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ROSE) <span class="co"># For SMOTE</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ranger) <span class="co"># A fast implementation of random forests</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="co"># For stacking/ensemble models</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stacks)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(themis)</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gghighlight)</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pscl)</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ResourceSelection)</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rcompanion)</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Hmisc)</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pROC)</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(cvAUC)</span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="possible-issues-and-conflicts-to-resolve" class="level4">
<h4 class="anchored" data-anchor-id="possible-issues-and-conflicts-to-resolve">1.1.1 Possible Issues and conflicts to resolve</h4>
<div class="sourceCode" id="cb3"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{bash}</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
</section>
<section id="load-data" class="level3">
<h3 class="anchored" data-anchor-id="load-data">1.2 Load Data</h3>
<p>Will be using my original Dataset as well Steve’s Dataset and compare for differences.</p>
<ul>
<li><strong>Renan</strong>: kaggle_data1</li>
<li><strong>Steve</strong>: stroke1</li>
</ul>
<section id="renan-dataset" class="level4">
<h4 class="anchored" data-anchor-id="renan-dataset">1.2.1 Renan Dataset</h4>
<p>Below will be loading the healthcare-dataset-stroke-data.csv and performing necessary changes to the dataset and loading into the DataFrame: kaggle_data1</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>find_git_root <span class="ot">&lt;-</span> <span class="cf">function</span>(<span class="at">start =</span> <span class="fu">getwd</span>()) {</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  path <span class="ot">&lt;-</span> <span class="fu">normalizePath</span>(start, <span class="at">winslash =</span> <span class="st">"/"</span>, <span class="at">mustWork =</span> <span class="cn">TRUE</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="cf">while</span> (path <span class="sc">!=</span> <span class="fu">dirname</span>(path)) {</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="fu">dir.exists</span>(<span class="fu">file.path</span>(path, <span class="st">".git"</span>))) <span class="fu">return</span>(path)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    path <span class="ot">&lt;-</span> <span class="fu">dirname</span>(path)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stop</span>(<span class="st">"No .git directory found — are you inside a Git repository?"</span>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>repo_root <span class="ot">&lt;-</span> <span class="fu">find_git_root</span>()</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>datasets_path <span class="ot">&lt;-</span> <span class="fu">file.path</span>(repo_root, <span class="st">"datasets"</span>)</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>kaggle_dataset_path <span class="ot">&lt;-</span> <span class="fu">file.path</span>(datasets_path, <span class="st">"kaggle-healthcare-dataset-stroke-data/healthcare-dataset-stroke-data.csv"</span>)</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>kaggle_data1 <span class="ot">=</span> <span class="fu">read_csv</span>(kaggle_dataset_path, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a><span class="co"># unique(kaggle_data1$bmi)</span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>kaggle_data1 <span class="ot">&lt;-</span> kaggle_data1 <span class="sc">%&gt;%</span></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">bmi =</span> <span class="fu">na_if</span>(bmi, <span class="st">"N/A"</span>)) <span class="sc">%&gt;%</span>   <span class="co"># Convert "N/A" string to NA</span></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">bmi =</span> <span class="fu">as.numeric</span>(bmi))         <span class="co"># Convert from character to numeric</span></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove the 'Other' gender row and the 'id' column</span></span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>kaggle_data1 <span class="ot">&lt;-</span> kaggle_data1 <span class="sc">%&gt;%</span></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(gender <span class="sc">!=</span> <span class="st">"Other"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>id) <span class="sc">%&gt;%</span></span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_if</span>(is.character, as.factor) <span class="co"># Convert character columns to factors for easier modeling</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="steve-dataset" class="level4">
<h4 class="anchored" data-anchor-id="steve-dataset">1.2.1 Steve Dataset</h4>
<p>Below will be loading the stroke.csv and performing necessary changes to the dataset and loading into the DataFrame: stroke1</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reading the datafile in (the same one you got for us Renan)#</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>steve_dataset_path <span class="ot">&lt;-</span> <span class="fu">file.path</span>(datasets_path, <span class="st">"steve/stroke.csv"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>stroke1 <span class="ot">=</span> <span class="fu">read_csv</span>(steve_dataset_path, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
</section>
<section id="prepare-dataset" class="level3">
<h3 class="anchored" data-anchor-id="prepare-dataset">1.3 Prepare Dataset</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(stroke1)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(stroke1)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(stroke1)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>count_tables <span class="ot">&lt;-</span> <span class="fu">lapply</span>(stroke1, table)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>count_tables</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Part 1: preparing the data</p>
<ul>
<li><strong>Smoking Status</strong> - remove unknown</li>
<li><strong>bmi</strong> - remove N/A</li>
<li><strong>Work type</strong> - remove children</li>
<li><strong>age</strong> - create numerical variable with 2 places after the decimal</li>
<li><strong>gender</strong> - remove other</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>stroke1[stroke1 <span class="sc">==</span> <span class="st">"N/A"</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>stroke1[stroke1 <span class="sc">==</span> <span class="st">"Unknown"</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>stroke1[stroke1 <span class="sc">==</span> <span class="st">"children"</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>stroke1[stroke1 <span class="sc">==</span> <span class="st">"other"</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>bmi <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">as.numeric</span>(stroke1<span class="sc">$</span>bmi), <span class="dv">2</span>)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>gender[stroke1<span class="sc">$</span>gender <span class="sc">==</span> <span class="st">"Male"</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>gender[stroke1<span class="sc">$</span>gender <span class="sc">==</span> <span class="st">"Female"</span>] <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>gender <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(stroke1<span class="sc">$</span>gender)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: NAs introduced by coercion</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>ever_married[stroke1<span class="sc">$</span>ever_married <span class="sc">==</span> <span class="st">"Yes"</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>ever_married[stroke1<span class="sc">$</span>ever_married <span class="sc">==</span> <span class="st">"No"</span>] <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>ever_married <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(stroke1<span class="sc">$</span>ever_married)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>work_type[stroke1<span class="sc">$</span>work_type <span class="sc">==</span> <span class="st">"Govt_job"</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>work_type[stroke1<span class="sc">$</span>work_type <span class="sc">==</span> <span class="st">"Private"</span>] <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>work_type[stroke1<span class="sc">$</span>work_type <span class="sc">==</span> <span class="st">"Self-employed"</span>] <span class="ot">&lt;-</span> <span class="dv">3</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>work_type[stroke1<span class="sc">$</span>work_type <span class="sc">==</span> <span class="st">"Never_worked"</span>] <span class="ot">&lt;-</span> <span class="dv">4</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>work_type <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(stroke1<span class="sc">$</span>work_type)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>Residence_type[stroke1<span class="sc">$</span>Residence_type <span class="sc">==</span> <span class="st">"Urban"</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>Residence_type[stroke1<span class="sc">$</span>Residence_type <span class="sc">==</span> <span class="st">"Rural"</span>] <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>Residence_type <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(stroke1<span class="sc">$</span>Residence_type)</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>avg_glucose_level <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(stroke1<span class="sc">$</span>avg_glucose_level)</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>heart_disease <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(stroke1<span class="sc">$</span>heart_disease)</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>hypertension <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(stroke1<span class="sc">$</span>hypertension)</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>age <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">as.numeric</span>(stroke1<span class="sc">$</span>age), <span class="dv">2</span>)</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>stroke <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(stroke1<span class="sc">$</span>stroke)</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>smoking_status[stroke1<span class="sc">$</span>smoking_status <span class="sc">==</span> <span class="st">"never smoked"</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>smoking_status[stroke1<span class="sc">$</span>smoking_status <span class="sc">==</span> <span class="st">"formerly smoked"</span>] <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>smoking_status[stroke1<span class="sc">$</span>smoking_status <span class="sc">==</span> <span class="st">"smokes"</span>] <span class="ot">&lt;-</span> <span class="dv">3</span></span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>smoking_status <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(stroke1<span class="sc">$</span>smoking_status)</span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a>stroke1 <span class="ot">&lt;-</span> stroke1[, <span class="sc">!</span>(<span class="fu">names</span>(stroke1) <span class="sc">%in%</span> <span class="st">"id"</span>)]</span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a>stroke1_clean <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(stroke1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>converted all columns to numeric and removed id</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># converted all columns to numeric and removed id</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(stroke1_clean)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(stroke1_clean)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>LR_stroke1 <span class="ot">&lt;-</span> stroke1_clean</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(LR_stroke1)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>count_tables <span class="ot">&lt;-</span> <span class="fu">lapply</span>(LR_stroke1, table)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>count_tables</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="apply-logistic-regression" class="level2">
<h2 class="anchored" data-anchor-id="apply-logistic-regression">2. Apply Logistic Regression</h2>
<p>Part 2:Create and Run the Logistic Regression model from the dataset</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Part 2:Create and Run the Logistic Regression model from the  dataset</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">glm</span>(stroke <span class="sc">~</span> gender <span class="sc">+</span> age <span class="sc">+</span> hypertension <span class="sc">+</span> heart_disease <span class="sc">+</span> ever_married <span class="sc">+</span> work_type <span class="sc">+</span> Residence_type <span class="sc">+</span> avg_glucose_level <span class="sc">+</span> bmi <span class="sc">+</span> smoking_status, <span class="at">data=</span>LR_stroke1, <span class="at">family =</span> binomial)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = stroke ~ gender + age + hypertension + heart_disease + 
    ever_married + work_type + Residence_type + avg_glucose_level + 
    bmi + smoking_status, family = binomial, data = LR_stroke1)

Coefficients:
                   Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)       -8.426854   0.873243  -9.650  &lt; 2e-16 ***
gender             0.080370   0.167274   0.480 0.630893    
age                0.070967   0.006845  10.368  &lt; 2e-16 ***
hypertension       0.570797   0.182580   3.126 0.001770 ** 
heart_disease      0.417884   0.220311   1.897 0.057856 .  
ever_married       0.174316   0.261832   0.666 0.505569    
work_type         -0.109615   0.126101  -0.869 0.384703    
Residence_type     0.005932   0.162188   0.037 0.970822    
avg_glucose_level  0.004658   0.001375   3.388 0.000704 ***
bmi                0.006275   0.012875   0.487 0.625954    
smoking_status     0.179921   0.106431   1.691 0.090932 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1403.5  on 3356  degrees of freedom
Residual deviance: 1145.4  on 3346  degrees of freedom
AIC: 1167.4

Number of Fisher Scoring iterations: 7</code></pre>
</div>
</div>
</section>
<section id="testing-logistic-regression-model-assumptions" class="level2">
<h2 class="anchored" data-anchor-id="testing-logistic-regression-model-assumptions">3. Testing logistic Regression Model Assumptions</h2>
<p>Part 3: Testing logistic Regression Model Assumptions</p>
<p>There are several assumptions for Logistic Regression. They are:</p>
<ol type="1">
<li>The Dependent Variable is binary (i.e, 0 or 1)</li>
<li>There is a linear relationship between th logit of the outcome and each predictor</li>
<li>There are NO high leverage outliers in the predictors</li>
<li>There is No high multicollinearity (ie strong correlations) between predictors</li>
</ol>
<p>Now to test each assumption</p>
<section id="testing-assumption-1" class="level3">
<h3 class="anchored" data-anchor-id="testing-assumption-1">3.1 Testing Assumption 1</h3>
<p>Testing Assumption 1: The Dependent Variable is binary (0 or 1)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(LR_stroke1<span class="sc">$</span>stroke)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1 0</code></pre>
</div>
</div>
</section>
<section id="testing-assumption-2" class="level3">
<h3 class="anchored" data-anchor-id="testing-assumption-2">3.2 Testing Assumption 2</h3>
<p>Testing Assumption 2: There is a linear relationship between the outcome variable and each predictor</p>
<p>first, adjust all predictors so all values are positive</p>
<p>Conclusion: For all continuous variables , <strong>ageadj</strong>, <strong>avg_glucose_leveladj</strong>, and <strong>bmiadj</strong>, the residual plots show linearity</p>
<p>Conclusion: all the other predictors are categorical, with the magenta line flat, and the values clustering around certain values, they are also appropriate for logistic regression</p>
<p>Conclusion for assumption 2 - Linearity is met</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>LR_stroke1<span class="sc">$</span>genderadj <span class="ot">&lt;-</span> LR_stroke1<span class="sc">$</span>gender <span class="sc">+</span> <span class="fu">abs</span>(<span class="fu">min</span>(LR_stroke1<span class="sc">$</span>gender)) <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>LR_stroke1<span class="sc">$</span>ageadj <span class="ot">&lt;-</span> LR_stroke1<span class="sc">$</span>age <span class="sc">+</span> <span class="fu">abs</span>(<span class="fu">min</span>(LR_stroke1<span class="sc">$</span>age)) <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>LR_stroke1<span class="sc">$</span>hypertensionadj <span class="ot">&lt;-</span> LR_stroke1<span class="sc">$</span>hypertension <span class="sc">+</span> <span class="fu">abs</span>(<span class="fu">min</span>(LR_stroke1<span class="sc">$</span>hypertension)) <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>LR_stroke1<span class="sc">$</span>heart_diseaseadj <span class="ot">&lt;-</span> LR_stroke1<span class="sc">$</span>heart_disease <span class="sc">+</span> <span class="fu">abs</span>(<span class="fu">min</span>(LR_stroke1<span class="sc">$</span>hypertension)) <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>LR_stroke1<span class="sc">$</span>ever_marriedadj <span class="ot">&lt;-</span> LR_stroke1<span class="sc">$</span>ever_married <span class="sc">+</span> <span class="fu">abs</span>(<span class="fu">min</span>(LR_stroke1<span class="sc">$</span>ever_married)) <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>LR_stroke1<span class="sc">$</span>work_typeadj <span class="ot">&lt;-</span> LR_stroke1<span class="sc">$</span>work_type <span class="sc">+</span> <span class="fu">abs</span>(<span class="fu">min</span>(LR_stroke1<span class="sc">$</span>work_type)) <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>LR_stroke1<span class="sc">$</span>Residence_typeadj <span class="ot">&lt;-</span> LR_stroke1<span class="sc">$</span>Residence_type <span class="sc">+</span> <span class="fu">abs</span>(<span class="fu">min</span>(LR_stroke1<span class="sc">$</span>Residence_type)) <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>LR_stroke1<span class="sc">$</span>avg_glucose_leveladj <span class="ot">&lt;-</span> LR_stroke1<span class="sc">$</span>avg_glucose_level <span class="sc">+</span> <span class="fu">abs</span>(<span class="fu">min</span>(LR_stroke1<span class="sc">$</span>avg_glucose_level)) <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>LR_stroke1<span class="sc">$</span>bmiadj <span class="ot">&lt;-</span> LR_stroke1<span class="sc">$</span>bmi <span class="sc">+</span> <span class="fu">abs</span>(<span class="fu">min</span>(LR_stroke1<span class="sc">$</span>bmi)) <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>LR_stroke1<span class="sc">$</span>smoking_statusadj <span class="ot">&lt;-</span> LR_stroke1<span class="sc">$</span>smoking_status <span class="sc">+</span> <span class="fu">abs</span>(<span class="fu">min</span>(LR_stroke1<span class="sc">$</span>smoking_status)) <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(LR_stroke1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [3,357 × 21] (S3: tbl_df/tbl/data.frame)
 $ gender              : num [1:3357] 1 1 2 2 1 1 2 2 2 2 ...
 $ age                 : num [1:3357] 67 80 49 79 81 74 69 81 61 54 ...
 $ hypertension        : num [1:3357] 0 0 0 1 0 1 0 1 0 0 ...
 $ heart_disease       : num [1:3357] 1 1 0 0 0 1 0 0 1 0 ...
 $ ever_married        : num [1:3357] 1 1 1 1 1 1 2 1 1 1 ...
 $ work_type           : num [1:3357] 2 2 2 3 2 2 2 2 1 2 ...
 $ Residence_type      : num [1:3357] 1 2 1 2 1 2 1 2 2 1 ...
 $ avg_glucose_level   : num [1:3357] 229 106 171 174 186 ...
 $ bmi                 : num [1:3357] 36.6 32.5 34.4 24 29 27.4 22.8 29.7 36.8 27.3 ...
 $ smoking_status      : num [1:3357] 2 1 3 1 2 1 1 1 3 3 ...
 $ stroke              : num [1:3357] 1 1 1 1 1 1 1 1 1 1 ...
 $ genderadj           : num [1:3357] 3 3 4 4 3 3 4 4 4 4 ...
 $ ageadj              : num [1:3357] 81 94 63 93 95 88 83 95 75 68 ...
 $ hypertensionadj     : num [1:3357] 1 1 1 2 1 2 1 2 1 1 ...
 $ heart_diseaseadj    : num [1:3357] 2 2 1 1 1 2 1 1 2 1 ...
 $ ever_marriedadj     : num [1:3357] 3 3 3 3 3 3 4 3 3 3 ...
 $ work_typeadj        : num [1:3357] 4 4 4 5 4 4 4 4 3 4 ...
 $ Residence_typeadj   : num [1:3357] 3 4 3 4 3 4 3 4 4 3 ...
 $ avg_glucose_leveladj: num [1:3357] 285 162 227 230 242 ...
 $ bmiadj              : num [1:3357] 49.1 45 46.9 36.5 41.5 39.9 35.3 42.2 49.3 39.8 ...
 $ smoking_statusadj   : num [1:3357] 4 3 5 3 4 3 3 3 5 5 ...
 - attr(*, "na.action")= 'omit' Named int [1:1753] 2 9 10 14 20 24 28 30 32 39 ...
  ..- attr(*, "names")= chr [1:1753] "2" "9" "10" "14" ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>StrokeAdj <span class="ot">&lt;-</span> LR_stroke1</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>StrokeAdj <span class="ot">&lt;-</span> StrokeAdj[ , <span class="sc">!</span>(<span class="fu">names</span>(StrokeAdj) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"gender"</span>, <span class="st">"age"</span>, <span class="st">"hypertension"</span>, <span class="st">"heart_disease"</span>, <span class="st">"ever_married"</span>, <span class="st">"work_type"</span>, <span class="st">"Residence_type"</span>, <span class="st">"avg_glucose_level"</span>, <span class="st">"bmi"</span>, <span class="st">"smoking_status"</span>)) ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Fit the model</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>mod<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">glm</span>(stroke <span class="sc">~</span> genderadj <span class="sc">+</span> ageadj <span class="sc">+</span> hypertensionadj <span class="sc">+</span> heart_diseaseadj <span class="sc">+</span> ever_marriedadj <span class="sc">+</span> work_typeadj <span class="sc">+</span> Residence_typeadj <span class="sc">+</span> avg_glucose_leveladj <span class="sc">+</span> bmiadj <span class="sc">+</span> smoking_statusadj, <span class="at">data=</span>StrokeAdj, <span class="at">family=</span>binomial)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot Residuals</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">residualPlots</span>(mod<span class="fl">.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Stroke_Results_10182025_SW_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Stroke_Results_10182025_SW_files/figure-html/unnamed-chunk-10-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                     Test stat Pr(&gt;|Test stat|)  
genderadj               0.0000          1.00000  
ageadj                  2.0626          0.15095  
hypertensionadj         0.0000          1.00000  
heart_diseaseadj        0.0000          1.00000  
ever_marriedadj         0.0000          1.00000  
work_typeadj            3.1406          0.07636 .
Residence_typeadj       0.0000          1.00000  
avg_glucose_leveladj    0.0103          0.91921  
bmiadj                  0.3947          0.52983  
smoking_statusadj       0.4775          0.48953  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="testing-assumption-3" class="level3">
<h3 class="anchored" data-anchor-id="testing-assumption-3">3.3 Testing Assumption 3</h3>
<p>Testing Assumption 3: assess influential outliers using car package and influencePlot</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Where the Object Stroke.2 comes from</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="co"># alias(Stroke.2)</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">alias</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Model :
stroke ~ gender + age + hypertension + heart_disease + ever_married + 
    work_type + Residence_type + avg_glucose_level + bmi + smoking_status</code></pre>
</div>
</div>
</section>
</section>
<section id="error---object-not-found" class="level2 callout-Note">
<h2 class="anchored" data-anchor-id="error---object-not-found">Error - Object not found</h2>
<p>Error: object ‘Stroke.2’ not found. Where is it coming from ??</p>
</section>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("Hmisc")</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="co"># library(Hmisc)</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">rcorr</span>(<span class="fu">as.matrix</span>(LR_stroke1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     gender   age hypertension heart_disease ever_married
gender                 1.00 -0.06        -0.04         -0.10         0.03
age                   -0.06  1.00         0.26          0.26        -0.49
hypertension          -0.04  0.26         1.00          0.11        -0.11
heart_disease         -0.10  0.26         0.11          1.00        -0.07
ever_married           0.03 -0.49        -0.11         -0.07         1.00
work_type              0.01  0.14         0.05          0.03        -0.02
Residence_type        -0.01 -0.02         0.00         -0.01         0.01
avg_glucose_level     -0.07  0.24         0.17          0.14        -0.12
bmi                   -0.02  0.04         0.13          0.00        -0.13
smoking_status        -0.08  0.03        -0.01          0.06        -0.06
stroke                -0.01  0.24         0.14          0.14        -0.07
genderadj              1.00 -0.06        -0.04         -0.10         0.03
ageadj                -0.06  1.00         0.26          0.26        -0.49
hypertensionadj       -0.04  0.26         1.00          0.11        -0.11
heart_diseaseadj      -0.10  0.26         0.11          1.00        -0.07
ever_marriedadj        0.03 -0.49        -0.11         -0.07         1.00
work_typeadj           0.01  0.14         0.05          0.03        -0.02
Residence_typeadj     -0.01 -0.02         0.00         -0.01         0.01
avg_glucose_leveladj  -0.07  0.24         0.17          0.14        -0.12
bmiadj                -0.02  0.04         0.13          0.00        -0.13
smoking_statusadj     -0.08  0.03        -0.01          0.06        -0.06
                     work_type Residence_type avg_glucose_level   bmi
gender                    0.01          -0.01             -0.07 -0.02
age                       0.14          -0.02              0.24  0.04
hypertension              0.05           0.00              0.17  0.13
heart_disease             0.03          -0.01              0.14  0.00
ever_married             -0.02           0.01             -0.12 -0.13
work_type                 1.00          -0.01              0.03 -0.02
Residence_type           -0.01           1.00              0.01  0.01
avg_glucose_level         0.03           0.01              1.00  0.16
bmi                      -0.02           0.01              0.16  1.00
smoking_status           -0.02          -0.04              0.01  0.03
stroke                    0.04          -0.01              0.14  0.01
genderadj                 0.01          -0.01             -0.07 -0.02
ageadj                    0.14          -0.02              0.24  0.04
hypertensionadj           0.05           0.00              0.17  0.13
heart_diseaseadj          0.03          -0.01              0.14  0.00
ever_marriedadj          -0.02           0.01             -0.12 -0.13
work_typeadj              1.00          -0.01              0.03 -0.02
Residence_typeadj        -0.01           1.00              0.01  0.01
avg_glucose_leveladj      0.03           0.01              1.00  0.16
bmiadj                   -0.02           0.01              0.16  1.00
smoking_statusadj        -0.02          -0.04              0.01  0.03
                     smoking_status stroke genderadj ageadj hypertensionadj
gender                        -0.08  -0.01      1.00  -0.06           -0.04
age                            0.03   0.24     -0.06   1.00            0.26
hypertension                  -0.01   0.14     -0.04   0.26            1.00
heart_disease                  0.06   0.14     -0.10   0.26            0.11
ever_married                  -0.06  -0.07      0.03  -0.49           -0.11
work_type                     -0.02   0.04      0.01   0.14            0.05
Residence_type                -0.04  -0.01     -0.01  -0.02            0.00
avg_glucose_level              0.01   0.14     -0.07   0.24            0.17
bmi                            0.03   0.01     -0.02   0.04            0.13
smoking_status                 1.00   0.02     -0.08   0.03           -0.01
stroke                         0.02   1.00     -0.01   0.24            0.14
genderadj                     -0.08  -0.01      1.00  -0.06           -0.04
ageadj                         0.03   0.24     -0.06   1.00            0.26
hypertensionadj               -0.01   0.14     -0.04   0.26            1.00
heart_diseaseadj               0.06   0.14     -0.10   0.26            0.11
ever_marriedadj               -0.06  -0.07      0.03  -0.49           -0.11
work_typeadj                  -0.02   0.04      0.01   0.14            0.05
Residence_typeadj             -0.04  -0.01     -0.01  -0.02            0.00
avg_glucose_leveladj           0.01   0.14     -0.07   0.24            0.17
bmiadj                         0.03   0.01     -0.02   0.04            0.13
smoking_statusadj              1.00   0.02     -0.08   0.03           -0.01
                     heart_diseaseadj ever_marriedadj work_typeadj
gender                          -0.10            0.03         0.01
age                              0.26           -0.49         0.14
hypertension                     0.11           -0.11         0.05
heart_disease                    1.00           -0.07         0.03
ever_married                    -0.07            1.00        -0.02
work_type                        0.03           -0.02         1.00
Residence_type                  -0.01            0.01        -0.01
avg_glucose_level                0.14           -0.12         0.03
bmi                              0.00           -0.13        -0.02
smoking_status                   0.06           -0.06        -0.02
stroke                           0.14           -0.07         0.04
genderadj                       -0.10            0.03         0.01
ageadj                           0.26           -0.49         0.14
hypertensionadj                  0.11           -0.11         0.05
heart_diseaseadj                 1.00           -0.07         0.03
ever_marriedadj                 -0.07            1.00        -0.02
work_typeadj                     0.03           -0.02         1.00
Residence_typeadj               -0.01            0.01        -0.01
avg_glucose_leveladj             0.14           -0.12         0.03
bmiadj                           0.00           -0.13        -0.02
smoking_statusadj                0.06           -0.06        -0.02
                     Residence_typeadj avg_glucose_leveladj bmiadj
gender                           -0.01                -0.07  -0.02
age                              -0.02                 0.24   0.04
hypertension                      0.00                 0.17   0.13
heart_disease                    -0.01                 0.14   0.00
ever_married                      0.01                -0.12  -0.13
work_type                        -0.01                 0.03  -0.02
Residence_type                    1.00                 0.01   0.01
avg_glucose_level                 0.01                 1.00   0.16
bmi                               0.01                 0.16   1.00
smoking_status                   -0.04                 0.01   0.03
stroke                           -0.01                 0.14   0.01
genderadj                        -0.01                -0.07  -0.02
ageadj                           -0.02                 0.24   0.04
hypertensionadj                   0.00                 0.17   0.13
heart_diseaseadj                 -0.01                 0.14   0.00
ever_marriedadj                   0.01                -0.12  -0.13
work_typeadj                     -0.01                 0.03  -0.02
Residence_typeadj                 1.00                 0.01   0.01
avg_glucose_leveladj              0.01                 1.00   0.16
bmiadj                            0.01                 0.16   1.00
smoking_statusadj                -0.04                 0.01   0.03
                     smoking_statusadj
gender                           -0.08
age                               0.03
hypertension                     -0.01
heart_disease                     0.06
ever_married                     -0.06
work_type                        -0.02
Residence_type                   -0.04
avg_glucose_level                 0.01
bmi                               0.03
smoking_status                    1.00
stroke                            0.02
genderadj                        -0.08
ageadj                            0.03
hypertensionadj                  -0.01
heart_diseaseadj                  0.06
ever_marriedadj                  -0.06
work_typeadj                     -0.02
Residence_typeadj                -0.04
avg_glucose_leveladj              0.01
bmiadj                            0.03
smoking_statusadj                 1.00

n= 3357 


P
                     gender age    hypertension heart_disease ever_married
gender                      0.0012 0.0204       0.0000        0.1140      
age                  0.0012        0.0000       0.0000        0.0000      
hypertension         0.0204 0.0000              0.0000        0.0000      
heart_disease        0.0000 0.0000 0.0000                     0.0000      
ever_married         0.1140 0.0000 0.0000       0.0000                    
work_type            0.3863 0.0000 0.0051       0.0862        0.2313      
Residence_type       0.5077 0.3076 0.8569       0.5527        0.5150      
avg_glucose_level    0.0000 0.0000 0.0000       0.0000        0.0000      
bmi                  0.2487 0.0144 0.0000       0.8185        0.0000      
smoking_status       0.0000 0.0448 0.7537       0.0005        0.0009      
stroke               0.4296 0.0000 0.0000       0.0000        0.0002      
genderadj            0.0000 0.0012 0.0204       0.0000        0.1140      
ageadj               0.0012 0.0000 0.0000       0.0000        0.0000      
hypertensionadj      0.0204 0.0000 0.0000       0.0000        0.0000      
heart_diseaseadj     0.0000 0.0000 0.0000       0.0000        0.0000      
ever_marriedadj      0.1140 0.0000 0.0000       0.0000        0.0000      
work_typeadj         0.3863 0.0000 0.0051       0.0862        0.2313      
Residence_typeadj    0.5077 0.3076 0.8569       0.5527        0.5150      
avg_glucose_leveladj 0.0000 0.0000 0.0000       0.0000        0.0000      
bmiadj               0.2487 0.0144 0.0000       0.8185        0.0000      
smoking_statusadj    0.0000 0.0448 0.7537       0.0005        0.0009      
                     work_type Residence_type avg_glucose_level bmi   
gender               0.3863    0.5077         0.0000            0.2487
age                  0.0000    0.3076         0.0000            0.0144
hypertension         0.0051    0.8569         0.0000            0.0000
heart_disease        0.0862    0.5527         0.0000            0.8185
ever_married         0.2313    0.5150         0.0000            0.0000
work_type                      0.6768         0.0467            0.3243
Residence_type       0.6768                   0.6427            0.5689
avg_glucose_level    0.0467    0.6427                           0.0000
bmi                  0.3243    0.5689         0.0000                  
smoking_status       0.3764    0.0208         0.7679            0.0925
stroke               0.0259    0.7171         0.0000            0.6866
genderadj            0.3863    0.5077         0.0000            0.2487
ageadj               0.0000    0.3076         0.0000            0.0144
hypertensionadj      0.0051    0.8569         0.0000            0.0000
heart_diseaseadj     0.0862    0.5527         0.0000            0.8185
ever_marriedadj      0.2313    0.5150         0.0000            0.0000
work_typeadj         0.0000    0.6768         0.0467            0.3243
Residence_typeadj    0.6768    0.0000         0.6427            0.5689
avg_glucose_leveladj 0.0467    0.6427         0.0000            0.0000
bmiadj               0.3243    0.5689         0.0000            0.0000
smoking_statusadj    0.3764    0.0208         0.7679            0.0925
                     smoking_status stroke genderadj ageadj hypertensionadj
gender               0.0000         0.4296 0.0000    0.0012 0.0204         
age                  0.0448         0.0000 0.0012    0.0000 0.0000         
hypertension         0.7537         0.0000 0.0204    0.0000 0.0000         
heart_disease        0.0005         0.0000 0.0000    0.0000 0.0000         
ever_married         0.0009         0.0002 0.1140    0.0000 0.0000         
work_type            0.3764         0.0259 0.3863    0.0000 0.0051         
Residence_type       0.0208         0.7171 0.5077    0.3076 0.8569         
avg_glucose_level    0.7679         0.0000 0.0000    0.0000 0.0000         
bmi                  0.0925         0.6866 0.2487    0.0144 0.0000         
smoking_status                      0.2559 0.0000    0.0448 0.7537         
stroke               0.2559                0.4296    0.0000 0.0000         
genderadj            0.0000         0.4296           0.0012 0.0204         
ageadj               0.0448         0.0000 0.0012           0.0000         
hypertensionadj      0.7537         0.0000 0.0204    0.0000                
heart_diseaseadj     0.0005         0.0000 0.0000    0.0000 0.0000         
ever_marriedadj      0.0009         0.0002 0.1140    0.0000 0.0000         
work_typeadj         0.3764         0.0259 0.3863    0.0000 0.0051         
Residence_typeadj    0.0208         0.7171 0.5077    0.3076 0.8569         
avg_glucose_leveladj 0.7679         0.0000 0.0000    0.0000 0.0000         
bmiadj               0.0925         0.6866 0.2487    0.0144 0.0000         
smoking_statusadj    0.0000         0.2559 0.0000    0.0448 0.7537         
                     heart_diseaseadj ever_marriedadj work_typeadj
gender               0.0000           0.1140          0.3863      
age                  0.0000           0.0000          0.0000      
hypertension         0.0000           0.0000          0.0051      
heart_disease        0.0000           0.0000          0.0862      
ever_married         0.0000           0.0000          0.2313      
work_type            0.0862           0.2313          0.0000      
Residence_type       0.5527           0.5150          0.6768      
avg_glucose_level    0.0000           0.0000          0.0467      
bmi                  0.8185           0.0000          0.3243      
smoking_status       0.0005           0.0009          0.3764      
stroke               0.0000           0.0002          0.0259      
genderadj            0.0000           0.1140          0.3863      
ageadj               0.0000           0.0000          0.0000      
hypertensionadj      0.0000           0.0000          0.0051      
heart_diseaseadj                      0.0000          0.0862      
ever_marriedadj      0.0000                           0.2313      
work_typeadj         0.0862           0.2313                      
Residence_typeadj    0.5527           0.5150          0.6768      
avg_glucose_leveladj 0.0000           0.0000          0.0467      
bmiadj               0.8185           0.0000          0.3243      
smoking_statusadj    0.0005           0.0009          0.3764      
                     Residence_typeadj avg_glucose_leveladj bmiadj
gender               0.5077            0.0000               0.2487
age                  0.3076            0.0000               0.0144
hypertension         0.8569            0.0000               0.0000
heart_disease        0.5527            0.0000               0.8185
ever_married         0.5150            0.0000               0.0000
work_type            0.6768            0.0467               0.3243
Residence_type       0.0000            0.6427               0.5689
avg_glucose_level    0.6427            0.0000               0.0000
bmi                  0.5689            0.0000               0.0000
smoking_status       0.0208            0.7679               0.0925
stroke               0.7171            0.0000               0.6866
genderadj            0.5077            0.0000               0.2487
ageadj               0.3076            0.0000               0.0144
hypertensionadj      0.8569            0.0000               0.0000
heart_diseaseadj     0.5527            0.0000               0.8185
ever_marriedadj      0.5150            0.0000               0.0000
work_typeadj         0.6768            0.0467               0.3243
Residence_typeadj                      0.6427               0.5689
avg_glucose_leveladj 0.6427                                 0.0000
bmiadj               0.5689            0.0000                     
smoking_statusadj    0.0208            0.7679               0.0925
                     smoking_statusadj
gender               0.0000           
age                  0.0448           
hypertension         0.7537           
heart_disease        0.0005           
ever_married         0.0009           
work_type            0.3764           
Residence_type       0.0208           
avg_glucose_level    0.7679           
bmi                  0.0925           
smoking_status       0.0000           
stroke               0.2559           
genderadj            0.0000           
ageadj               0.0448           
hypertensionadj      0.7537           
heart_diseaseadj     0.0005           
ever_marriedadj      0.0009           
work_typeadj         0.3764           
Residence_typeadj    0.0208           
avg_glucose_leveladj 0.7679           
bmiadj               0.0925           
smoking_statusadj                     </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("car")</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="co"># library(car)</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">influencePlot</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Stroke_Results_10182025_SW_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>        StudRes          Hat       CookD
83    2.6917353 0.0039267816 0.012237368
84    1.5018344 0.0343771041 0.006641860
87    3.0732709 0.0012042796 0.011476828
131   3.1608870 0.0006013465 0.007697762
152   3.1135601 0.0005613972 0.006237531
2583 -0.8509399 0.0399302730 0.001668526</code></pre>
</div>
</div>
<p>Cooks D ranges from 0 to .0122</p>
<p>While the ideal size is 4/N (4/3357 = 0.012), its far outside the danger zone of .5</p>
<p>Conclusion: Assumption 3 is met - No substantial outliers</p>
<section id="testing-assumption-4" class="level3">
<h3 class="anchored" data-anchor-id="testing-assumption-4">3.4 Testing Assumption 4</h3>
<p>Testing Assumption 4 : Multicollinearity using vif in the CAR package</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           gender               age      hypertension     heart_disease 
         1.041499          1.213552          1.051213          1.083661 
     ever_married         work_type    Residence_type avg_glucose_level 
         1.018892          1.051698          1.006965          1.105268 
              bmi    smoking_status 
         1.117138          1.049260 </code></pre>
</div>
</div>
<p>Conclusion. All vif values are below 5 or 10. Ideally most values should be around 1. Range for all the predictors is between: 1.01 - 1.21. Way below the danger threshold of 5 to 10.</p>
<p>Conclusion: No Multicollinearity</p>
<p>Final Conclusion: All 4 assumptions are met, logistic regression is a valid model</p>
</section>
<section id="analysis-of-the-model" class="level2">
<h2 class="anchored" data-anchor-id="analysis-of-the-model">4 Analysis of the Model</h2>
<p>Part 4: Analysis of the Model</p>
<p>There are 2 issues with the model. Fit and Predictive Capability</p>
<section id="use-hosmer-lemesho-and-naglekerke-r" class="level3">
<h3 class="anchored" data-anchor-id="use-hosmer-lemesho-and-naglekerke-r">4.1 Use Hosmer-lemesho and Naglekerke R</h3>
<p>Part 1 fit. Use Hosmer-lemesho and Naglekerke R for non technical audience</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("ResourceSelection")</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="co"># library(ResourceSelection)</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hoslem.test</span>(model<span class="sc">$</span>y, <span class="fu">fitted</span>(model), <span class="at">g =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Hosmer and Lemeshow goodness of fit (GOF) test

data:  model$y, fitted(model)
X-squared = 5.2704, df = 8, p-value = 0.7283</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("rcompanion")</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="co"># library(rcompanion)</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">nagelkerke</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$Models
                                                                                                                                                                               
Model: "glm, stroke ~ gender + age + hypertension + heart_disease + ever_married + work_type + Residence_type + avg_glucose_level + bmi + smoking_status, binomial, LR_stroke1"
Null:  "glm, stroke ~ 1, binomial, LR_stroke1"                                                                                                                                 

$Pseudo.R.squared.for.model.vs.null
                             Pseudo.R.squared
McFadden                            0.1838790
Cox and Snell (ML)                  0.0739944
Nagelkerke (Cragg and Uhler)        0.2165560

$Likelihood.ratio.test
 Df.diff LogLik.diff  Chisq    p.value
     -10     -129.03 258.07 1.0892e-49

$Number.of.observations
           
Model: 3357
Null:  3357

$Messages
[1] "Note: For models fit with REML, these statistics are based on refitting with ML"

$Warnings
[1] "None"</code></pre>
</div>
</div>
</section>
<section id="predictive-capability" class="level3">
<h3 class="anchored" data-anchor-id="predictive-capability">4.2 Predictive Capability</h3>
<p>Part 2 - Predictive Capability</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("pROC")</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="co"># library(pROC)</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>probs <span class="ot">&lt;-</span> <span class="fu">predict</span>(model, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>roc_obj <span class="ot">&lt;-</span> <span class="fu">roc</span>(LR_stroke1<span class="sc">$</span>stroke, probs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting levels: control = 0, case = 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting direction: controls &lt; cases</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">auc</span>(roc_obj)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Area under the curve: 0.8285</code></pre>
</div>
</div>
<p>Predict AUC cross validation</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Need to implement AUC cross validation
</div>
</div>
<div class="callout-body-container callout-body">
<p>Could not understand yet how to implement the AUC cross validation</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict AUC cross validation</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("cvAUC")</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="co"># library(cvAUC)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Confusion Matrix</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Confusion Matrix</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>LR_stroke1<span class="sc">$</span>gender <span class="ot">&lt;-</span> <span class="fu">factor</span>(LR_stroke1<span class="sc">$</span>gender)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>LR_stroke1<span class="sc">$</span>hypertension <span class="ot">&lt;-</span> <span class="fu">factor</span>(LR_stroke1<span class="sc">$</span>hypertension)</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>LR_stroke1<span class="sc">$</span>heart_disease <span class="ot">&lt;-</span> <span class="fu">factor</span>(LR_stroke1<span class="sc">$</span>heart_disease)</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>LR_stroke1<span class="sc">$</span>ever_married <span class="ot">&lt;-</span> <span class="fu">factor</span>(LR_stroke1<span class="sc">$</span>ever_married)</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>LR_stroke1<span class="sc">$</span>work_type <span class="ot">&lt;-</span> <span class="fu">factor</span>(LR_stroke1<span class="sc">$</span>work_type)</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>LR_stroke1<span class="sc">$</span>Residence_type <span class="ot">&lt;-</span> <span class="fu">factor</span>(LR_stroke1<span class="sc">$</span>Residence_type)</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>LR_stroke1<span class="sc">$</span>smoking_status <span class="ot">&lt;-</span> <span class="fu">factor</span>(LR_stroke1<span class="sc">$</span>smoking_status)</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>LR_stroke1<span class="sc">$</span>stroke <span class="ot">&lt;-</span> <span class="fu">factor</span>(LR_stroke1<span class="sc">$</span>stroke)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>fit logistic regression model</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fit logistic regression model</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>model_CM <span class="ot">&lt;-</span> <span class="fu">glm</span>(stroke <span class="sc">~</span> gender <span class="sc">+</span> age <span class="sc">+</span> hypertension <span class="sc">+</span> heart_disease <span class="sc">+</span> ever_married <span class="sc">+</span> work_type <span class="sc">+</span> Residence_type <span class="sc">+</span> avg_glucose_level <span class="sc">+</span> bmi <span class="sc">+</span> smoking_status, <span class="at">data=</span>LR_stroke1, <span class="at">family =</span> binomial)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Get Predicted Probabilities for each observation</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get Predicted Probabilities for each observation</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>pred_prob <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_CM, <span class="at">type =</span> <span class="st">"response"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>At threshold of around 0.5</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Classify prediction using a threshold (0.5 is common but can adjust)</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="co"># at threshold of 0.5</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>pred_class <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">ifelse</span>(pred_prob <span class="sc">&gt;</span> <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">0</span>), <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>conf_matrix <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(pred_class, <span class="fu">factor</span>(LR_stroke1<span class="sc">$</span>stroke, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"0"</span>, <span class="st">"1"</span>)), <span class="at">positive =</span> <span class="st">"1"</span>)</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(conf_matrix)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction    0    1
         0 3176  179
         1    1    1
                                          
               Accuracy : 0.9464          
                 95% CI : (0.9382, 0.9538)
    No Information Rate : 0.9464          
    P-Value [Acc &gt; NIR] : 0.5198          
                                          
                  Kappa : 0.0098          
                                          
 Mcnemar's Test P-Value : &lt;2e-16          
                                          
            Sensitivity : 0.0055556       
            Specificity : 0.9996852       
         Pos Pred Value : 0.5000000       
         Neg Pred Value : 0.9466468       
             Prevalence : 0.0536193       
         Detection Rate : 0.0002979       
   Detection Prevalence : 0.0005958       
      Balanced Accuracy : 0.5026204       
                                          
       'Positive' Class : 1               
                                          </code></pre>
</div>
</div>
<p>IF 1 row is all 0’s then model doesn’t show any predictability</p>
<p><strong>At threshold of 0.3</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># at threshold of 0.3</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>pred_class <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">ifelse</span>(pred_prob <span class="sc">&gt;</span> <span class="fl">0.3</span>, <span class="dv">1</span>, <span class="dv">0</span>), <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>conf_matrix <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(pred_class, <span class="fu">factor</span>(LR_stroke1<span class="sc">$</span>stroke, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"0"</span>, <span class="st">"1"</span>)), <span class="at">positive =</span> <span class="st">"1"</span>)</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(conf_matrix)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction    0    1
         0 3140  164
         1   37   16
                                          
               Accuracy : 0.9401          
                 95% CI : (0.9316, 0.9479)
    No Information Rate : 0.9464          
    P-Value [Acc &gt; NIR] : 0.9483          
                                          
                  Kappa : 0.1158          
                                          
 Mcnemar's Test P-Value : &lt;2e-16          
                                          
            Sensitivity : 0.088889        
            Specificity : 0.988354        
         Pos Pred Value : 0.301887        
         Neg Pred Value : 0.950363        
             Prevalence : 0.053619        
         Detection Rate : 0.004766        
   Detection Prevalence : 0.015788        
      Balanced Accuracy : 0.538621        
                                          
       'Positive' Class : 1               
                                          </code></pre>
</div>
</div>
<p>IF 1 row is all 0’s then model doesn’t show any predictability</p>
<p><strong>At threshold of 0.2</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># at threshold of 0.2</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>pred_class <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">ifelse</span>(pred_prob <span class="sc">&gt;</span> <span class="fl">0.2</span>, <span class="dv">1</span>, <span class="dv">0</span>), <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>conf_matrix <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(pred_class, <span class="fu">factor</span>(LR_stroke1<span class="sc">$</span>stroke, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"0"</span>, <span class="st">"1"</span>)), <span class="at">positive =</span> <span class="st">"1"</span>)</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(conf_matrix)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction    0    1
         0 3040  134
         1  137   46
                                          
               Accuracy : 0.9193          
                 95% CI : (0.9095, 0.9283)
    No Information Rate : 0.9464          
    P-Value [Acc &gt; NIR] : 1.0000          
                                          
                  Kappa : 0.2108          
                                          
 Mcnemar's Test P-Value : 0.9033          
                                          
            Sensitivity : 0.25556         
            Specificity : 0.95688         
         Pos Pred Value : 0.25137         
         Neg Pred Value : 0.95778         
             Prevalence : 0.05362         
         Detection Rate : 0.01370         
   Detection Prevalence : 0.05451         
      Balanced Accuracy : 0.60622         
                                          
       'Positive' Class : 1               
                                          </code></pre>
</div>
</div>
<p>IF 1 row is all 0’s then model doesn’t show any predictability</p>
<p><strong>At threshold of 0.18</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># At Threshold of 0.18</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>pred_class <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">ifelse</span>(pred_prob <span class="sc">&gt;</span> <span class="fl">0.18</span>, <span class="dv">1</span>, <span class="dv">0</span>), <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>conf_matrix <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(pred_class, <span class="fu">factor</span>(LR_stroke1<span class="sc">$</span>stroke, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"0"</span>, <span class="st">"1"</span>)), <span class="at">positive =</span> <span class="st">"1"</span>)</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(conf_matrix)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction    0    1
         0 3003  126
         1  174   54
                                          
               Accuracy : 0.9106          
                 95% CI : (0.9005, 0.9201)
    No Information Rate : 0.9464          
    P-Value [Acc &gt; NIR] : 1.000000        
                                          
                  Kappa : 0.2178          
                                          
 Mcnemar's Test P-Value : 0.006657        
                                          
            Sensitivity : 0.30000         
            Specificity : 0.94523         
         Pos Pred Value : 0.23684         
         Neg Pred Value : 0.95973         
             Prevalence : 0.05362         
         Detection Rate : 0.01609         
   Detection Prevalence : 0.06792         
      Balanced Accuracy : 0.62262         
                                          
       'Positive' Class : 1               
                                          </code></pre>
</div>
</div>
<p><strong>At threshold of 0.15</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># At threshold of 0.15</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>pred_class <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">ifelse</span>(pred_prob <span class="sc">&gt;</span> <span class="fl">0.15</span>, <span class="dv">1</span>, <span class="dv">0</span>), <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>conf_matrix <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(pred_class, <span class="fu">factor</span>(LR_stroke1<span class="sc">$</span>stroke, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"0"</span>, <span class="st">"1"</span>)), <span class="at">positive =</span> <span class="st">"1"</span>)</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(conf_matrix)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction    0    1
         0 2917  102
         1  260   78
                                          
               Accuracy : 0.8922          
                 95% CI : (0.8812, 0.9025)
    No Information Rate : 0.9464          
    P-Value [Acc &gt; NIR] : 1               
                                          
                  Kappa : 0.2486          
                                          
 Mcnemar's Test P-Value : &lt;2e-16          
                                          
            Sensitivity : 0.43333         
            Specificity : 0.91816         
         Pos Pred Value : 0.23077         
         Neg Pred Value : 0.96621         
             Prevalence : 0.05362         
         Detection Rate : 0.02324         
   Detection Prevalence : 0.10069         
      Balanced Accuracy : 0.67575         
                                          
       'Positive' Class : 1               
                                          </code></pre>
</div>
</div>
<p>at threshold of 0.6 that starts the models predictability</p>
<p><strong>At threshold of 0.1</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># at threshold of 0.1#</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>pred_class <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">ifelse</span>(pred_prob <span class="sc">&gt;</span> <span class="fl">0.1</span>, <span class="dv">1</span>, <span class="dv">0</span>), <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>conf_matrix <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(pred_class, <span class="fu">factor</span>(LR_stroke1<span class="sc">$</span>stroke, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"0"</span>, <span class="st">"1"</span>)), <span class="at">positive =</span> <span class="st">"1"</span>)</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(conf_matrix)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction    0    1
         0 2683   69
         1  494  111
                                          
               Accuracy : 0.8323          
                 95% CI : (0.8192, 0.8448)
    No Information Rate : 0.9464          
    P-Value [Acc &gt; NIR] : 1               
                                          
                  Kappa : 0.2182          
                                          
 Mcnemar's Test P-Value : &lt;2e-16          
                                          
            Sensitivity : 0.61667         
            Specificity : 0.84451         
         Pos Pred Value : 0.18347         
         Neg Pred Value : 0.97493         
             Prevalence : 0.05362         
         Detection Rate : 0.03307         
   Detection Prevalence : 0.18022         
      Balanced Accuracy : 0.73059         
                                          
       'Positive' Class : 1               
                                          </code></pre>
</div>
</div>
<p><strong>At threshold of 0.05</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># at threshold of 0.05#</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>pred_class <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">ifelse</span>(pred_prob <span class="sc">&gt;</span> <span class="fl">0.05</span>, <span class="dv">1</span>, <span class="dv">0</span>), <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>conf_matrix <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(pred_class, <span class="fu">factor</span>(LR_stroke1<span class="sc">$</span>stroke, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"0"</span>, <span class="st">"1"</span>)), <span class="at">positive =</span> <span class="st">"1"</span>)</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(conf_matrix)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction    0    1
         0 2256   37
         1  921  143
                                         
               Accuracy : 0.7146         
                 95% CI : (0.699, 0.7299)
    No Information Rate : 0.9464         
    P-Value [Acc &gt; NIR] : 1              
                                         
                  Kappa : 0.1521         
                                         
 Mcnemar's Test P-Value : &lt;2e-16         
                                         
            Sensitivity : 0.79444        
            Specificity : 0.71010        
         Pos Pred Value : 0.13440        
         Neg Pred Value : 0.98386        
             Prevalence : 0.05362        
         Detection Rate : 0.04260        
   Detection Prevalence : 0.31695        
      Balanced Accuracy : 0.75227        
                                         
       'Positive' Class : 1              
                                         </code></pre>
</div>
</div>
<p>Generate Confusion Matrix comparing model predictions to actual outcome</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Confused about this code chunk
</div>
</div>
<div class="callout-body-container callout-body">
<p>This code serves no purpose at all</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Generate Confusion Matrix comparing model predictions to actual outcome</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("caret")</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="co"># library(caret)</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>conf_matrix <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(pred_class, <span class="fu">factor</span>(LR_stroke1<span class="sc">$</span>stroke, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"0"</span>, <span class="st">"1"</span>)), <span class="at">positive =</span> <span class="st">"1"</span>)</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(conf_matrix)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction    0    1
         0 2256   37
         1  921  143
                                         
               Accuracy : 0.7146         
                 95% CI : (0.699, 0.7299)
    No Information Rate : 0.9464         
    P-Value [Acc &gt; NIR] : 1              
                                         
                  Kappa : 0.1521         
                                         
 Mcnemar's Test P-Value : &lt;2e-16         
                                         
            Sensitivity : 0.79444        
            Specificity : 0.71010        
         Pos Pred Value : 0.13440        
         Neg Pred Value : 0.98386        
             Prevalence : 0.05362        
         Detection Rate : 0.04260        
   Detection Prevalence : 0.31695        
      Balanced Accuracy : 0.75227        
                                         
       'Positive' Class : 1              
                                         </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Error
</div>
</div>
<div class="callout-body-container callout-body">
<p>Error: <code>data</code> and <code>reference</code> should be factors with the same levels.</p>
</div>
</div>
<div class="sourceCode" id="cb58"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>conf_matrix <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(pred_class, LR_stroke1, <span class="at">positive =</span> <span class="st">"1"</span>)</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(conf_matrix)</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Error: <code>data</code> and <code>reference</code> should be factors with the same levels.</p>
<p>Suppose you have your folds and predictions for each fold</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Suppose you have your folds and predictions for each fold</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Error: object 'folds' not found</span></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>cvAUC<span class="sc">::</span><span class="fu">cvAUC</span>(predictions, labels, <span class="at">folds =</span> folds)</span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Error
</div>
</div>
<div class="callout-body-container callout-body">
<p>Error: object ‘folds’ not found</p>
</div>
</div>
</section>
</section>
<section id="original-code" class="level2">
<h2 class="anchored" data-anchor-id="original-code">Original Code</h2>
<p>Below we see the Original Code shared by Steve: <strong>Stroke_Results_1019_2025_latest_440PM_SW_For_Group.R</strong></p>
<div class="sourceCode" id="cb60"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"dplyr"</span>)</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"car"</span>)</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"ResourceSelection"</span>)</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ResourceSelection)</span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a>stroke1 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"D:</span><span class="sc">\\</span><span class="st">stroke.csv"</span>)</span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(stroke1)</span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(stroke1)</span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(stroke1)</span>
<span id="cb60-12"><a href="#cb60-12" aria-hidden="true" tabindex="-1"></a>count_tables <span class="ot">&lt;-</span> <span class="fu">lapply</span>(stroke1, table)</span>
<span id="cb60-13"><a href="#cb60-13" aria-hidden="true" tabindex="-1"></a>count_tables</span>
<span id="cb60-14"><a href="#cb60-14" aria-hidden="true" tabindex="-1"></a><span class="co">#-------------------------------------------Part 1:  preparing the data---------------------------------#</span></span>
<span id="cb60-15"><a href="#cb60-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Smoking Status - remove unknown#</span></span>
<span id="cb60-16"><a href="#cb60-16" aria-hidden="true" tabindex="-1"></a><span class="co">#bmi - remove N/A#</span></span>
<span id="cb60-17"><a href="#cb60-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Work type - remove children#</span></span>
<span id="cb60-18"><a href="#cb60-18" aria-hidden="true" tabindex="-1"></a><span class="co"># age create numerical variable with 2 places after the decimal#</span></span>
<span id="cb60-19"><a href="#cb60-19" aria-hidden="true" tabindex="-1"></a><span class="co">#gender -remove other#</span></span>
<span id="cb60-20"><a href="#cb60-20" aria-hidden="true" tabindex="-1"></a>stroke1[stroke1 <span class="sc">==</span> <span class="st">"N/A"</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb60-21"><a href="#cb60-21" aria-hidden="true" tabindex="-1"></a>stroke1[stroke1 <span class="sc">==</span> <span class="st">"Unknown"</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb60-22"><a href="#cb60-22" aria-hidden="true" tabindex="-1"></a>stroke1[stroke1 <span class="sc">==</span> <span class="st">"children"</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb60-23"><a href="#cb60-23" aria-hidden="true" tabindex="-1"></a>stroke1[stroke1 <span class="sc">==</span> <span class="st">"other"</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb60-24"><a href="#cb60-24" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>bmi <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">as.numeric</span>(stroke1<span class="sc">$</span>bmi), <span class="dv">2</span>)</span>
<span id="cb60-25"><a href="#cb60-25" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>gender[stroke1<span class="sc">$</span>gender <span class="sc">==</span> <span class="st">"Male"</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb60-26"><a href="#cb60-26" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>gender[stroke1<span class="sc">$</span>gender <span class="sc">==</span> <span class="st">"Female"</span>] <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb60-27"><a href="#cb60-27" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>gender <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(stroke1<span class="sc">$</span>gender)</span>
<span id="cb60-28"><a href="#cb60-28" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>ever_married[stroke1<span class="sc">$</span>ever_married <span class="sc">==</span> <span class="st">"Yes"</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb60-29"><a href="#cb60-29" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>ever_married[stroke1<span class="sc">$</span>ever_married <span class="sc">==</span> <span class="st">"No"</span>] <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb60-30"><a href="#cb60-30" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>ever_married <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(stroke1<span class="sc">$</span>ever_married)</span>
<span id="cb60-31"><a href="#cb60-31" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>work_type[stroke1<span class="sc">$</span>work_type <span class="sc">==</span> <span class="st">"Govt_job"</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb60-32"><a href="#cb60-32" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>work_type[stroke1<span class="sc">$</span>work_type <span class="sc">==</span> <span class="st">"Private"</span>] <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb60-33"><a href="#cb60-33" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>work_type[stroke1<span class="sc">$</span>work_type <span class="sc">==</span> <span class="st">"Self-employed"</span>] <span class="ot">&lt;-</span> <span class="dv">3</span></span>
<span id="cb60-34"><a href="#cb60-34" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>work_type[stroke1<span class="sc">$</span>work_type <span class="sc">==</span> <span class="st">"Never_worked"</span>] <span class="ot">&lt;-</span> <span class="dv">4</span></span>
<span id="cb60-35"><a href="#cb60-35" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>work_type <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(stroke1<span class="sc">$</span>work_type)</span>
<span id="cb60-36"><a href="#cb60-36" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>Residence_type[stroke1<span class="sc">$</span>Residence_type <span class="sc">==</span> <span class="st">"Urban"</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb60-37"><a href="#cb60-37" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>Residence_type[stroke1<span class="sc">$</span>Residence_type <span class="sc">==</span> <span class="st">"Rural"</span>] <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb60-38"><a href="#cb60-38" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>Residence_type <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(stroke1<span class="sc">$</span>Residence_type)</span>
<span id="cb60-39"><a href="#cb60-39" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>avg_glucose_level <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(stroke1<span class="sc">$</span>avg_glucose_level)</span>
<span id="cb60-40"><a href="#cb60-40" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>heart_disease <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(stroke1<span class="sc">$</span>heart_disease)</span>
<span id="cb60-41"><a href="#cb60-41" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>hypertension <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(stroke1<span class="sc">$</span>hypertension)</span>
<span id="cb60-42"><a href="#cb60-42" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>age <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">as.numeric</span>(stroke1<span class="sc">$</span>age), <span class="dv">2</span>)</span>
<span id="cb60-43"><a href="#cb60-43" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>stroke <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(stroke1<span class="sc">$</span>stroke)</span>
<span id="cb60-44"><a href="#cb60-44" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>smoking_status[stroke1<span class="sc">$</span>smoking_status <span class="sc">==</span> <span class="st">"never smoked"</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb60-45"><a href="#cb60-45" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>smoking_status[stroke1<span class="sc">$</span>smoking_status <span class="sc">==</span> <span class="st">"formerly smoked"</span>] <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb60-46"><a href="#cb60-46" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>smoking_status[stroke1<span class="sc">$</span>smoking_status <span class="sc">==</span> <span class="st">"smokes"</span>] <span class="ot">&lt;-</span> <span class="dv">3</span></span>
<span id="cb60-47"><a href="#cb60-47" aria-hidden="true" tabindex="-1"></a>stroke1<span class="sc">$</span>smoking_status <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(stroke1<span class="sc">$</span>smoking_status)</span>
<span id="cb60-48"><a href="#cb60-48" aria-hidden="true" tabindex="-1"></a>stroke1 <span class="ot">&lt;-</span> stroke1[, <span class="sc">!</span>(<span class="fu">names</span>(stroke1) <span class="sc">%in%</span> <span class="st">"id"</span>)]</span>
<span id="cb60-49"><a href="#cb60-49" aria-hidden="true" tabindex="-1"></a>stroke1_clean <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(stroke1)</span>
<span id="cb60-50"><a href="#cb60-50" aria-hidden="true" tabindex="-1"></a><span class="co">#converted all columns to numeric and removed id#</span></span>
<span id="cb60-51"><a href="#cb60-51" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(stroke1_clean)</span>
<span id="cb60-52"><a href="#cb60-52" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(stroke1_clean)</span>
<span id="cb60-53"><a href="#cb60-53" aria-hidden="true" tabindex="-1"></a>LR_stroke1 <span class="ot">&lt;-</span> stroke1_clean</span>
<span id="cb60-54"><a href="#cb60-54" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(LR_stroke1)</span>
<span id="cb60-55"><a href="#cb60-55" aria-hidden="true" tabindex="-1"></a><span class="co">#-------------------------Part 2:Create and Run the Logistic Regression model from the  dataset-------------#</span></span>
<span id="cb60-56"><a href="#cb60-56" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">glm</span>(stroke <span class="sc">~</span> gender <span class="sc">+</span> age <span class="sc">+</span> hypertension <span class="sc">+</span> heart_disease <span class="sc">+</span> ever_married <span class="sc">+</span> work_type <span class="sc">+</span> Residence_type <span class="sc">+</span> avg_glucose_level <span class="sc">+</span> bmi <span class="sc">+</span> smoking_status, <span class="at">data=</span>LR_stroke1, <span class="at">family =</span> binomial)</span>
<span id="cb60-57"><a href="#cb60-57" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span>
<span id="cb60-58"><a href="#cb60-58" aria-hidden="true" tabindex="-1"></a><span class="co"># ----------------------------------Part 3: Testing logistic Regression Model Assumptions------------------------#</span></span>
<span id="cb60-59"><a href="#cb60-59" aria-hidden="true" tabindex="-1"></a><span class="co"># There are several assumptions for Logistic Regression#</span></span>
<span id="cb60-60"><a href="#cb60-60" aria-hidden="true" tabindex="-1"></a><span class="co"># They are:#</span></span>
<span id="cb60-61"><a href="#cb60-61" aria-hidden="true" tabindex="-1"></a><span class="co">#(1) The Dependent Variable is binary (i.e, 0 or 1)#</span></span>
<span id="cb60-62"><a href="#cb60-62" aria-hidden="true" tabindex="-1"></a><span class="co">#(2) There is a linear relationship between th logit of the outcome and each predictor#</span></span>
<span id="cb60-63"><a href="#cb60-63" aria-hidden="true" tabindex="-1"></a><span class="co">#(3) There are NO high leverage outliers in the predictors#</span></span>
<span id="cb60-64"><a href="#cb60-64" aria-hidden="true" tabindex="-1"></a><span class="co">#(4) There is No high multicollinearity (ie strong correlations) between predictors#</span></span>
<span id="cb60-65"><a href="#cb60-65" aria-hidden="true" tabindex="-1"></a><span class="do">####################################:Now to test each assumption: ################</span></span>
<span id="cb60-66"><a href="#cb60-66" aria-hidden="true" tabindex="-1"></a><span class="co"># Testing Assumption 1: The Dependent Variable is binary (0 or 1)#</span></span>
<span id="cb60-67"><a href="#cb60-67" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(LR_stroke1<span class="sc">$</span>stroke)</span>
<span id="cb60-68"><a href="#cb60-68" aria-hidden="true" tabindex="-1"></a><span class="co">#Testing Assumption 2: There is a linear relationship between the outcome variable and each predictor</span></span>
<span id="cb60-69"><a href="#cb60-69" aria-hidden="true" tabindex="-1"></a><span class="co">#first,  adjust all predictors so all values are positive#</span></span>
<span id="cb60-70"><a href="#cb60-70" aria-hidden="true" tabindex="-1"></a>LR_stroke1<span class="sc">$</span>genderadj <span class="ot">&lt;-</span> LR_stroke1<span class="sc">$</span>gender <span class="sc">+</span> <span class="fu">abs</span>(<span class="fu">min</span>(LR_stroke1<span class="sc">$</span>gender)) <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb60-71"><a href="#cb60-71" aria-hidden="true" tabindex="-1"></a>LR_stroke1<span class="sc">$</span>ageadj <span class="ot">&lt;-</span> LR_stroke1<span class="sc">$</span>age <span class="sc">+</span> <span class="fu">abs</span>(<span class="fu">min</span>(LR_stroke1<span class="sc">$</span>age)) <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb60-72"><a href="#cb60-72" aria-hidden="true" tabindex="-1"></a>LR_stroke1<span class="sc">$</span>hypertensionadj <span class="ot">&lt;-</span> LR_stroke1<span class="sc">$</span>hypertension <span class="sc">+</span> <span class="fu">abs</span>(<span class="fu">min</span>(LR_stroke1<span class="sc">$</span>hypertension)) <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb60-73"><a href="#cb60-73" aria-hidden="true" tabindex="-1"></a>LR_stroke1<span class="sc">$</span>heart_diseaseadj <span class="ot">&lt;-</span> LR_stroke1<span class="sc">$</span>heart_disease <span class="sc">+</span> <span class="fu">abs</span>(<span class="fu">min</span>(LR_stroke1<span class="sc">$</span>hypertension)) <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb60-74"><a href="#cb60-74" aria-hidden="true" tabindex="-1"></a>LR_stroke1<span class="sc">$</span>ever_marriedadj <span class="ot">&lt;-</span> LR_stroke1<span class="sc">$</span>ever_married <span class="sc">+</span> <span class="fu">abs</span>(<span class="fu">min</span>(LR_stroke1<span class="sc">$</span>ever_married)) <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb60-75"><a href="#cb60-75" aria-hidden="true" tabindex="-1"></a>LR_stroke1<span class="sc">$</span>work_typeadj <span class="ot">&lt;-</span> LR_stroke1<span class="sc">$</span>work_type <span class="sc">+</span> <span class="fu">abs</span>(<span class="fu">min</span>(LR_stroke1<span class="sc">$</span>work_type)) <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb60-76"><a href="#cb60-76" aria-hidden="true" tabindex="-1"></a>LR_stroke1<span class="sc">$</span>Residence_typeadj <span class="ot">&lt;-</span> LR_stroke1<span class="sc">$</span>Residence_type <span class="sc">+</span> <span class="fu">abs</span>(<span class="fu">min</span>(LR_stroke1<span class="sc">$</span>Residence_type)) <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb60-77"><a href="#cb60-77" aria-hidden="true" tabindex="-1"></a>LR_stroke1<span class="sc">$</span>avg_glucose_leveladj <span class="ot">&lt;-</span> LR_stroke1<span class="sc">$</span>avg_glucose_level <span class="sc">+</span> <span class="fu">abs</span>(<span class="fu">min</span>(LR_stroke1<span class="sc">$</span>avg_glucose_level)) <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb60-78"><a href="#cb60-78" aria-hidden="true" tabindex="-1"></a>LR_stroke1<span class="sc">$</span>bmiadj <span class="ot">&lt;-</span> LR_stroke1<span class="sc">$</span>bmi <span class="sc">+</span> <span class="fu">abs</span>(<span class="fu">min</span>(LR_stroke1<span class="sc">$</span>bmi)) <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb60-79"><a href="#cb60-79" aria-hidden="true" tabindex="-1"></a>LR_stroke1<span class="sc">$</span>smoking_statusadj <span class="ot">&lt;-</span> LR_stroke1<span class="sc">$</span>smoking_status <span class="sc">+</span> <span class="fu">abs</span>(<span class="fu">min</span>(LR_stroke1<span class="sc">$</span>smoking_status)) <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb60-80"><a href="#cb60-80" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(LR_stroke1)</span>
<span id="cb60-81"><a href="#cb60-81" aria-hidden="true" tabindex="-1"></a>StrokeAdj <span class="ot">&lt;-</span> LR_stroke1</span>
<span id="cb60-82"><a href="#cb60-82" aria-hidden="true" tabindex="-1"></a>StrokeAdj <span class="ot">&lt;-</span> StrokeAdj[ , <span class="sc">!</span>(<span class="fu">names</span>(StrokeAdj) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"gender"</span>, <span class="st">"age"</span>, <span class="st">"hypertension"</span>, <span class="st">"heart_disease"</span>, <span class="st">"ever_married"</span>, <span class="st">"work_type"</span>, <span class="st">"Residence_type"</span>, <span class="st">"avg_glucose_level"</span>, <span class="st">"bmi"</span>, <span class="st">"smoking_status"</span>)) ]</span>
<span id="cb60-83"><a href="#cb60-83" aria-hidden="true" tabindex="-1"></a>mod<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">glm</span>(stroke <span class="sc">~</span> genderadj <span class="sc">+</span> ageadj <span class="sc">+</span> hypertensionadj <span class="sc">+</span> heart_diseaseadj <span class="sc">+</span> ever_marriedadj <span class="sc">+</span> work_typeadj <span class="sc">+</span> Residence_typeadj <span class="sc">+</span> avg_glucose_leveladj <span class="sc">+</span> bmiadj <span class="sc">+</span> smoking_statusadj, <span class="at">data=</span>StrokeAdj, <span class="at">family=</span>binomial)</span>
<span id="cb60-84"><a href="#cb60-84" aria-hidden="true" tabindex="-1"></a><span class="fu">residualPlots</span>(mod<span class="fl">.2</span>)</span>
<span id="cb60-85"><a href="#cb60-85" aria-hidden="true" tabindex="-1"></a><span class="co"># Conclusion: For all continuous variables , ageadj, avg_glucose_leveladj, and bniadj, the residual plots show linearity#</span></span>
<span id="cb60-86"><a href="#cb60-86" aria-hidden="true" tabindex="-1"></a><span class="co"># Conclusion:all the other predictors are categorical, with the magenta line flat, and the values clustering around certain values, they are also appropriate for logistic regression#</span></span>
<span id="cb60-87"><a href="#cb60-87" aria-hidden="true" tabindex="-1"></a><span class="co"># ---------------------------------------Conclusion for assumption 2 - Linearity is met--------------------------------#</span></span>
<span id="cb60-88"><a href="#cb60-88" aria-hidden="true" tabindex="-1"></a><span class="co"># Testing Assumption 3: assess influential outliers using car package and influencePlot#</span></span>
<span id="cb60-89"><a href="#cb60-89" aria-hidden="true" tabindex="-1"></a><span class="fu">alias</span>(Stroke<span class="fl">.2</span>)</span>
<span id="cb60-90"><a href="#cb60-90" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"Hmisc"</span>)</span>
<span id="cb60-91"><a href="#cb60-91" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Hmisc)</span>
<span id="cb60-92"><a href="#cb60-92" aria-hidden="true" tabindex="-1"></a><span class="fu">rcorr</span>(<span class="fu">as.matrix</span>(LR_stroke1))</span>
<span id="cb60-93"><a href="#cb60-93" aria-hidden="true" tabindex="-1"></a><span class="fu">influencePlot</span>(model)</span>
<span id="cb60-94"><a href="#cb60-94" aria-hidden="true" tabindex="-1"></a><span class="co"># Cooks D ranges from 0 to .0122 While the ideal size is 4/N (4/3357 = 0.012), its far outside the danger zone of .5</span></span>
<span id="cb60-95"><a href="#cb60-95" aria-hidden="true" tabindex="-1"></a><span class="co">#--------------------------------- Conclusion: Assumption 3 is met - No substantial outliers---------------------#</span></span>
<span id="cb60-96"><a href="#cb60-96" aria-hidden="true" tabindex="-1"></a><span class="co"># Testing Assumption 4 : Multicollinearity using vif in the care package#</span></span>
<span id="cb60-97"><a href="#cb60-97" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(model)</span>
<span id="cb60-98"><a href="#cb60-98" aria-hidden="true" tabindex="-1"></a><span class="co">#--------------------Conclusion. All vif values are below  5 or 10. Ideally most values should be around 1. Range for all#</span></span>
<span id="cb60-99"><a href="#cb60-99" aria-hidden="true" tabindex="-1"></a><span class="co"># the predictors is between: 1.01 - 1.21. Way below the danger threshold of 5 to 10. Conclusion: No Multicollinearity####</span></span>
<span id="cb60-100"><a href="#cb60-100" aria-hidden="true" tabindex="-1"></a><span class="do">#####################################################################################################################</span></span>
<span id="cb60-101"><a href="#cb60-101" aria-hidden="true" tabindex="-1"></a><span class="co"># -----------------Final Conclusion: All4 assumptions are met, logistic regression is a valid model---------------#</span></span>
<span id="cb60-102"><a href="#cb60-102" aria-hidden="true" tabindex="-1"></a><span class="do">####################################################################################################################</span></span>
<span id="cb60-103"><a href="#cb60-103" aria-hidden="true" tabindex="-1"></a><span class="co"># ---------------------------------------------Part 4: Analysis of the Model----------------------------------------#</span></span>
<span id="cb60-104"><a href="#cb60-104" aria-hidden="true" tabindex="-1"></a><span class="co"># -----------------------There are 2 issues with the model. Fit and Predictive Capability---------------------------#</span></span>
<span id="cb60-105"><a href="#cb60-105" aria-hidden="true" tabindex="-1"></a><span class="co"># ----------------Part 1  fit. Use Hosmer-lemesho and Naglekerke R for non technical audience-------------------#</span></span>
<span id="cb60-106"><a href="#cb60-106" aria-hidden="true" tabindex="-1"></a><span class="fu">hoslem.test</span>(model<span class="sc">$</span>y, <span class="fu">fitted</span>(model), <span class="at">g =</span> <span class="dv">10</span>)</span>
<span id="cb60-107"><a href="#cb60-107" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"rcompanion"</span>)</span>
<span id="cb60-108"><a href="#cb60-108" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rcompanion)</span>
<span id="cb60-109"><a href="#cb60-109" aria-hidden="true" tabindex="-1"></a><span class="fu">nagelkerke</span>(model)</span>
<span id="cb60-110"><a href="#cb60-110" aria-hidden="true" tabindex="-1"></a><span class="co"># -----------------------Part 2 - Predictive Capability-----------------------------------------------------------</span></span>
<span id="cb60-111"><a href="#cb60-111" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"pROC"</span>)</span>
<span id="cb60-112"><a href="#cb60-112" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pROC)</span>
<span id="cb60-113"><a href="#cb60-113" aria-hidden="true" tabindex="-1"></a>probs <span class="ot">&lt;-</span> <span class="fu">predict</span>(model, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb60-114"><a href="#cb60-114" aria-hidden="true" tabindex="-1"></a>roc_obj <span class="ot">&lt;-</span> <span class="fu">roc</span>(LR_stroke1<span class="sc">$</span>stroke, probs)</span>
<span id="cb60-115"><a href="#cb60-115" aria-hidden="true" tabindex="-1"></a><span class="fu">auc</span>(roc_obj)</span>
<span id="cb60-116"><a href="#cb60-116" aria-hidden="true" tabindex="-1"></a><span class="co"># Predictict AUC cross validation</span></span>
<span id="cb60-117"><a href="#cb60-117" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"cvAUC"</span>)</span>
<span id="cb60-118"><a href="#cb60-118" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(cvAUC)</span>
<span id="cb60-119"><a href="#cb60-119" aria-hidden="true" tabindex="-1"></a><span class="co"># Confusion Matrix</span></span>
<span id="cb60-120"><a href="#cb60-120" aria-hidden="true" tabindex="-1"></a>LR_stroke1<span class="sc">$</span>gender <span class="ot">&lt;-</span> <span class="fu">factor</span>(LR_stroke1<span class="sc">$</span>gender)</span>
<span id="cb60-121"><a href="#cb60-121" aria-hidden="true" tabindex="-1"></a>LR_stroke1<span class="sc">$</span>hypertension <span class="ot">&lt;-</span> <span class="fu">factor</span>(LR_stroke1<span class="sc">$</span>hypertension)</span>
<span id="cb60-122"><a href="#cb60-122" aria-hidden="true" tabindex="-1"></a>LR_stroke1<span class="sc">$</span>heart_disease <span class="ot">&lt;-</span> <span class="fu">factor</span>(LR_stroke1<span class="sc">$</span>heart_disease)</span>
<span id="cb60-123"><a href="#cb60-123" aria-hidden="true" tabindex="-1"></a>LR_stroke1<span class="sc">$</span>ever_married <span class="ot">&lt;-</span> <span class="fu">factor</span>(LR_stroke1<span class="sc">$</span>ever_married)</span>
<span id="cb60-124"><a href="#cb60-124" aria-hidden="true" tabindex="-1"></a>LR_stroke1<span class="sc">$</span>work_type <span class="ot">&lt;-</span> <span class="fu">factor</span>(LR_stroke1<span class="sc">$</span>work_type)</span>
<span id="cb60-125"><a href="#cb60-125" aria-hidden="true" tabindex="-1"></a>LR_stroke1<span class="sc">$</span>Residence_type <span class="ot">&lt;-</span> <span class="fu">factor</span>(LR_stroke1<span class="sc">$</span>Residence_type)</span>
<span id="cb60-126"><a href="#cb60-126" aria-hidden="true" tabindex="-1"></a>LR_stroke1<span class="sc">$</span>smoking_status <span class="ot">&lt;-</span> <span class="fu">factor</span>(LR_stroke1<span class="sc">$</span>smoking_status)</span>
<span id="cb60-127"><a href="#cb60-127" aria-hidden="true" tabindex="-1"></a>LR_stroke1<span class="sc">$</span>stroke <span class="ot">&lt;-</span> <span class="fu">factor</span>(LR_stroke1<span class="sc">$</span>stroke)</span>
<span id="cb60-128"><a href="#cb60-128" aria-hidden="true" tabindex="-1"></a><span class="co"># fit logistic regression model</span></span>
<span id="cb60-129"><a href="#cb60-129" aria-hidden="true" tabindex="-1"></a>model_CM <span class="ot">&lt;-</span> <span class="fu">glm</span>(stroke <span class="sc">~</span> gender <span class="sc">+</span> age <span class="sc">+</span> hypertension <span class="sc">+</span> heart_disease <span class="sc">+</span> ever_married <span class="sc">+</span> work_type <span class="sc">+</span> Residence_type <span class="sc">+</span> avg_glucose_level <span class="sc">+</span> bmi <span class="sc">+</span> smoking_status, <span class="at">data=</span>LR_stroke1, <span class="at">family =</span> binomial)</span>
<span id="cb60-130"><a href="#cb60-130" aria-hidden="true" tabindex="-1"></a><span class="co"># Get Predicted Probabilities for each observation</span></span>
<span id="cb60-131"><a href="#cb60-131" aria-hidden="true" tabindex="-1"></a>pred_prob <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_CM, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb60-132"><a href="#cb60-132" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"caret"</span>)</span>
<span id="cb60-133"><a href="#cb60-133" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span>
<span id="cb60-134"><a href="#cb60-134" aria-hidden="true" tabindex="-1"></a><span class="co">#Classify prediction using a threshold (0.5 is common but can adjust)</span></span>
<span id="cb60-135"><a href="#cb60-135" aria-hidden="true" tabindex="-1"></a><span class="co"># art threshold of 0.5#</span></span>
<span id="cb60-136"><a href="#cb60-136" aria-hidden="true" tabindex="-1"></a>pred_class <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">ifelse</span>(pred_prob <span class="sc">&gt;</span> <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">0</span>), <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))</span>
<span id="cb60-137"><a href="#cb60-137" aria-hidden="true" tabindex="-1"></a>conf_matrix <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(pred_class, <span class="fu">factor</span>(LR_stroke1<span class="sc">$</span>stroke, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"0"</span>, <span class="st">"1"</span>)), <span class="at">positive =</span> <span class="st">"1"</span>)</span>
<span id="cb60-138"><a href="#cb60-138" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(conf_matrix)</span>
<span id="cb60-139"><a href="#cb60-139" aria-hidden="true" tabindex="-1"></a><span class="co"># at threshold of 0.3#</span></span>
<span id="cb60-140"><a href="#cb60-140" aria-hidden="true" tabindex="-1"></a>pred_class <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">ifelse</span>(pred_prob <span class="sc">&gt;</span> <span class="fl">0.3</span>, <span class="dv">1</span>, <span class="dv">0</span>), <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))</span>
<span id="cb60-141"><a href="#cb60-141" aria-hidden="true" tabindex="-1"></a>conf_matrix <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(pred_class, <span class="fu">factor</span>(LR_stroke1<span class="sc">$</span>stroke, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"0"</span>, <span class="st">"1"</span>)), <span class="at">positive =</span> <span class="st">"1"</span>)</span>
<span id="cb60-142"><a href="#cb60-142" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(conf_matrix)</span>
<span id="cb60-143"><a href="#cb60-143" aria-hidden="true" tabindex="-1"></a><span class="co"># at threshold of 0.2</span></span>
<span id="cb60-144"><a href="#cb60-144" aria-hidden="true" tabindex="-1"></a>pred_class <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">ifelse</span>(pred_prob <span class="sc">&gt;</span> <span class="fl">0.2</span>, <span class="dv">1</span>, <span class="dv">0</span>), <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))</span>
<span id="cb60-145"><a href="#cb60-145" aria-hidden="true" tabindex="-1"></a>conf_matrix <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(pred_class, <span class="fu">factor</span>(LR_stroke1<span class="sc">$</span>stroke, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"0"</span>, <span class="st">"1"</span>)), <span class="at">positive =</span> <span class="st">"1"</span>)</span>
<span id="cb60-146"><a href="#cb60-146" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(conf_matrix)</span>
<span id="cb60-147"><a href="#cb60-147" aria-hidden="true" tabindex="-1"></a><span class="co"># At Threshold of 0.18#</span></span>
<span id="cb60-148"><a href="#cb60-148" aria-hidden="true" tabindex="-1"></a>pred_class <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">ifelse</span>(pred_prob <span class="sc">&gt;</span> <span class="fl">0.18</span>, <span class="dv">1</span>, <span class="dv">0</span>), <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))</span>
<span id="cb60-149"><a href="#cb60-149" aria-hidden="true" tabindex="-1"></a>conf_matrix <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(pred_class, <span class="fu">factor</span>(LR_stroke1<span class="sc">$</span>stroke, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"0"</span>, <span class="st">"1"</span>)), <span class="at">positive =</span> <span class="st">"1"</span>)</span>
<span id="cb60-150"><a href="#cb60-150" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(conf_matrix)</span>
<span id="cb60-151"><a href="#cb60-151" aria-hidden="true" tabindex="-1"></a><span class="co"># At threshold of 0.15#</span></span>
<span id="cb60-152"><a href="#cb60-152" aria-hidden="true" tabindex="-1"></a>pred_class <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">ifelse</span>(pred_prob <span class="sc">&gt;</span> <span class="fl">0.15</span>, <span class="dv">1</span>, <span class="dv">0</span>), <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))</span>
<span id="cb60-153"><a href="#cb60-153" aria-hidden="true" tabindex="-1"></a>conf_matrix <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(pred_class, <span class="fu">factor</span>(LR_stroke1<span class="sc">$</span>stroke, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"0"</span>, <span class="st">"1"</span>)), <span class="at">positive =</span> <span class="st">"1"</span>)</span>
<span id="cb60-154"><a href="#cb60-154" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(conf_matrix)</span>
<span id="cb60-155"><a href="#cb60-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-156"><a href="#cb60-156" aria-hidden="true" tabindex="-1"></a><span class="co"># at threshold of 0.1#</span></span>
<span id="cb60-157"><a href="#cb60-157" aria-hidden="true" tabindex="-1"></a>pred_class <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">ifelse</span>(pred_prob <span class="sc">&gt;</span> <span class="fl">0.1</span>, <span class="dv">1</span>, <span class="dv">0</span>), <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))</span>
<span id="cb60-158"><a href="#cb60-158" aria-hidden="true" tabindex="-1"></a>conf_matrix <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(pred_class, <span class="fu">factor</span>(LR_stroke1<span class="sc">$</span>stroke, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"0"</span>, <span class="st">"1"</span>)), <span class="at">positive =</span> <span class="st">"1"</span>)</span>
<span id="cb60-159"><a href="#cb60-159" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(conf_matrix)</span>
<span id="cb60-160"><a href="#cb60-160" aria-hidden="true" tabindex="-1"></a><span class="co"># at threshold of 0.05#</span></span>
<span id="cb60-161"><a href="#cb60-161" aria-hidden="true" tabindex="-1"></a>pred_class <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">ifelse</span>(pred_prob <span class="sc">&gt;</span> <span class="fl">0.05</span>, <span class="dv">1</span>, <span class="dv">0</span>), <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))</span>
<span id="cb60-162"><a href="#cb60-162" aria-hidden="true" tabindex="-1"></a>conf_matrix <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(pred_class, <span class="fu">factor</span>(LR_stroke1<span class="sc">$</span>stroke, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"0"</span>, <span class="st">"1"</span>)), <span class="at">positive =</span> <span class="st">"1"</span>)</span>
<span id="cb60-163"><a href="#cb60-163" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(conf_matrix)</span>
<span id="cb60-164"><a href="#cb60-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-165"><a href="#cb60-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-166"><a href="#cb60-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-167"><a href="#cb60-167" aria-hidden="true" tabindex="-1"></a><span class="co">#Generate Confusion Matrix comparing model predictions to actual outcome</span></span>
<span id="cb60-168"><a href="#cb60-168" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"caret"</span>)</span>
<span id="cb60-169"><a href="#cb60-169" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span>
<span id="cb60-170"><a href="#cb60-170" aria-hidden="true" tabindex="-1"></a>conf_matrix <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(pred_class, <span class="fu">factor</span>(LR_stroke1<span class="sc">$</span>stroke, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"0"</span>, <span class="st">"1"</span>)), <span class="at">positive =</span> <span class="st">"1"</span>)</span>
<span id="cb60-171"><a href="#cb60-171" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(conf_matrix)</span>
<span id="cb60-172"><a href="#cb60-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-173"><a href="#cb60-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-174"><a href="#cb60-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-175"><a href="#cb60-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-176"><a href="#cb60-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-177"><a href="#cb60-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-178"><a href="#cb60-178" aria-hidden="true" tabindex="-1"></a>conf_matrix <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(pred_class, LR_stroke1, <span class="at">positive =</span> <span class="st">"1"</span>)</span>
<span id="cb60-179"><a href="#cb60-179" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(conf_matrix)</span>
<span id="cb60-180"><a href="#cb60-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-181"><a href="#cb60-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-182"><a href="#cb60-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-183"><a href="#cb60-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-184"><a href="#cb60-184" aria-hidden="true" tabindex="-1"></a><span class="co"># Suppose you have your folds and predictions for each fold</span></span>
<span id="cb60-185"><a href="#cb60-185" aria-hidden="true" tabindex="-1"></a>cvAUC<span class="sc">::</span><span class="fu">cvAUC</span>(predictions, labels, <span class="at">folds =</span> folds)</span>
<span id="cb60-186"><a href="#cb60-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-187"><a href="#cb60-187" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<section id="references" class="level3">
<h3 class="anchored" data-anchor-id="references">References</h3>
<div id="refs" role="list">

</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>