{
  "hash": "0a3186b85e0779948cf7afeb86b9b022",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Reproducing Steve's Code - Stroke_results_1019_2025_latest\"\ndescription: \"Trying to replicate the Stroke_results_1019_2025_latest\"\nauthor:\n  - name: Renan Monteiro Barbosa\n    url: https://github.com/renanmb\n    affiliation: Master of Data Science Program @ The University of West Florida (UWF)\n    # affiliation-url: https://ucsb-meds.github.io/\n# date: 10-24-2022\ncategories: [coding, week 8, renan]\n# citation:\n#   url: https://samanthacsik.github.io/posts/2022-10-24-my-blog-post/\nimage: images/spongebob-imagination.jpg\ndraft: false\nbibliography: references.bib\nlink-citations: true\n---\n\nOn this document I try to replicate Steve code: **Stroke_Results_1019_2025_latest_440PM_SW_For_Group.R**\n\n\n\n## 1. Setup and Data Loading\n\nFirst we need to install all packages, system dependencies and solve conflicts to produce a new renv.lock file.\n\n### 1.1 Load Libraries\n\nInstall packages if necessary:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Run this once to install all the necessary packages\n# install.packages(\"dplyr\")\n# install.packages(\"car\")\n# install.packages(\"ResourceSelection\")\n# install.packages(\"caret\")\n# install.packages(\"rcompanion\")\n# install.packages(\"pROC\")\n# install.packages(\"cvAUC\")\n```\n:::\n\n\nLoad Libraries:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# For data manipulation and visualization\nlibrary(tidyverse)\nlibrary(ggplot2)\nlibrary(corrplot)\nlibrary(knitr)\nlibrary(ggpubr)\n\n# For data preprocessing and modeling\nlibrary(mice)\nlibrary(ROSE) # For SMOTE\nlibrary(ranger) # A fast implementation of random forests\n\n# For stacking/ensemble models\nlibrary(stacks)\nlibrary(tidymodels)\n\nlibrary(themis)\nlibrary(gghighlight)\n\nlibrary(pscl)\nlibrary(dplyr)\nlibrary(car)\nlibrary(ResourceSelection)\nlibrary(caret)\nlibrary(rcompanion)\nlibrary(Hmisc)\nlibrary(pROC)\nlibrary(cvAUC)\n\n# Set seed for reproducibility\nset.seed(123)\n```\n:::\n\n\n#### 1.1.1 Possible Issues and conflicts to resolve\n\n```{{bash}}\n#| code-fold: true\n> # For data manipulation and visualization\n> library(tidyverse)\nlibrary(ggplot2)\nlibrary(corrplot)\nlibrary(knitr)\nlibrary(ggpubr)\n\n# For data preprocessing and modeling\nlibrary(mice)\nlibrary(ROSE) # For SMOTE\nlibrary(ranger) # A fast implementation of random forests\n\n# For stacking/ensemble models\nlibrary(stacks)\nlibrary(tidymodels)\n\nlibrary(themis)\nlibrary(gghighlight)\n\nlibrary(pscl)\nlibrary(dplyr)\nlibrary(car)\nlibrary(ResourceSelection)\nlibrary(caret)\nlibrary(rcompanion)\nlibrary(Hmisc)\nlibrary(pROC)\nlibrary(cvAUC)\n\n# Set seed for reproducibility\nset.seed(123)\n── Attaching core tidyverse packages ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   3.5.2     ✔ tibble    3.3.0\n✔ lubridate 1.9.4     ✔ tidyr     1.3.1\n✔ purrr     1.1.0     \n── Conflicts ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n> library(ggplot2)\n> library(corrplot)\ncorrplot 0.95 loaded\n> library(knitr)\n> library(ggpubr)\n> \n> # For data preprocessing and modeling\n> library(mice)\n\nAttaching package: ‘mice’\n\nThe following object is masked from ‘package:stats’:\n\n    filter\n\nThe following objects are masked from ‘package:base’:\n\n    cbind, rbind\n\n> library(ROSE) # For SMOTE\nLoaded ROSE 0.0-4\n\n> library(ranger) # A fast implementation of random forests\nranger 0.17.0 using 2 threads (default). Change with num.threads in ranger() and predict(), options(Ncpus = N), options(ranger.num.threads = N) or environment variable R_RANGER_NUM_THREADS.\n> \n> # For stacking/ensemble models\n> library(stacks)\nRegistered S3 method overwritten by 'butcher':\n  method                 from    \n  as.character.dev_topic generics\n> library(tidymodels)\n── Attaching packages ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidymodels 1.4.1 ──\n✔ broom        1.0.9     ✔ rsample      1.3.1\n✔ dials        1.4.2     ✔ tailor       0.1.0\n✔ infer        1.0.9     ✔ tune         2.0.0\n✔ modeldata    1.5.1     ✔ workflows    1.3.0\n✔ parsnip      1.3.3     ✔ workflowsets 1.1.1\n✔ recipes      1.3.1     ✔ yardstick    1.3.2\n── Conflicts ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidymodels_conflicts() ──\n✖ scales::discard() masks purrr::discard()\n✖ mice::filter()    masks dplyr::filter(), stats::filter()\n✖ recipes::fixed()  masks stringr::fixed()\n✖ dplyr::lag()      masks stats::lag()\n✖ yardstick::spec() masks readr::spec()\n✖ recipes::step()   masks stats::step()\n• Use tidymodels_prefer() to resolve common conflicts.\n> \n> library(themis)\n> library(gghighlight)\n> \n> library(pscl)\nClasses and Methods for R originally developed in the\nPolitical Science Computational Laboratory\nDepartment of Political Science\nStanford University (2002-2015),\nby and under the direction of Simon Jackman.\nhurdle and zeroinfl functions by Achim Zeileis.\n> library(dplyr)\n> library(car)\nLoading required package: carData\n\nAttaching package: ‘car’\n\nThe following object is masked from ‘package:dplyr’:\n\n    recode\n\nThe following object is masked from ‘package:purrr’:\n\n    some\n\n> library(ResourceSelection)\nResourceSelection 0.3-6          2023-06-27\n> library(caret)\nLoading required package: lattice\n\nAttaching package: ‘caret’\n\nThe following objects are masked from ‘package:yardstick’:\n\n    precision, recall, sensitivity, specificity\n\nThe following object is masked from ‘package:rsample’:\n\n    calibration\n\nThe following object is masked from ‘package:purrr’:\n\n    lift\n\n> library(rcompanion)\n\nAttaching package: ‘rcompanion’\n\nThe following object is masked from ‘package:yardstick’:\n\n    accuracy\n\n> library(Hmisc)\n\nAttaching package: ‘Hmisc’\n\nThe following object is masked from ‘package:parsnip’:\n\n    translate\n\nThe following objects are masked from ‘package:dplyr’:\n\n    src, summarize\n\nThe following objects are masked from ‘package:base’:\n\n    format.pval, units\n\n> library(pROC)\nType 'citation(\"pROC\")' for a citation.\n\nAttaching package: ‘pROC’\n\nThe following objects are masked from ‘package:stats’:\n\n    cov, smooth, var\n\n> library(cvAUC)\n> \n> # Set seed for reproducibility\n> set.seed(123)\n```\n\n\n### 1.2 Load Data\n\nWill be using my original Dataset as well Steve's Dataset and compare for differences.\n\n- **Renan**: kaggle_data1\n- **Steve**: stroke1\n\n#### 1.2.1 Renan Dataset\n\nBelow will be loading the healthcare-dataset-stroke-data.csv and performing necessary changes to the dataset and loading into the DataFrame: kaggle_data1\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nfind_git_root <- function(start = getwd()) {\n  path <- normalizePath(start, winslash = \"/\", mustWork = TRUE)\n  while (path != dirname(path)) {\n    if (dir.exists(file.path(path, \".git\"))) return(path)\n    path <- dirname(path)\n  }\n  stop(\"No .git directory found — are you inside a Git repository?\")\n}\n\nrepo_root <- find_git_root()\ndatasets_path <- file.path(repo_root, \"datasets\")\nkaggle_dataset_path <- file.path(datasets_path, \"kaggle-healthcare-dataset-stroke-data/healthcare-dataset-stroke-data.csv\")\nkaggle_data1 = read_csv(kaggle_dataset_path, show_col_types = FALSE)\n\n# unique(kaggle_data1$bmi)\nkaggle_data1 <- kaggle_data1 %>%\n  mutate(bmi = na_if(bmi, \"N/A\")) %>%   # Convert \"N/A\" string to NA\n  mutate(bmi = as.numeric(bmi))         # Convert from character to numeric\n\n# Remove the 'Other' gender row and the 'id' column\nkaggle_data1 <- kaggle_data1 %>%\n  filter(gender != \"Other\") %>%\n  select(-id) %>%\n  mutate_if(is.character, as.factor) # Convert character columns to factors for easier modeling\n```\n:::\n\n\n#### 1.2.1 Steve Dataset\n\nBelow will be loading the stroke.csv and performing necessary changes to the dataset and loading into the DataFrame: stroke1\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Reading the datafile in (the same one you got for us Renan)#\nsteve_dataset_path <- file.path(datasets_path, \"steve/stroke.csv\")\nstroke1 = read_csv(steve_dataset_path, show_col_types = FALSE)\n```\n:::\n\n\n### 1.3 Prepare Dataset\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(stroke1)\nnrow(stroke1)\nsummary(stroke1)\ncount_tables <- lapply(stroke1, table)\ncount_tables\n```\n:::\n\n\nPart 1:  preparing the data\n\n- **Smoking Status** - remove unknown\n- **bmi** - remove N/A\n- **Work type** - remove children\n- **age** - create numerical variable with 2 places after the decimal\n- **gender** - remove other\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstroke1[stroke1 == \"N/A\"] <- NA\nstroke1[stroke1 == \"Unknown\"] <- NA\nstroke1[stroke1 == \"children\"] <- NA\nstroke1[stroke1 == \"other\"] <- NA\n\nstroke1$bmi <- round(as.numeric(stroke1$bmi), 2)\n\nstroke1$gender[stroke1$gender == \"Male\"] <- 1\nstroke1$gender[stroke1$gender == \"Female\"] <- 2\nstroke1$gender <- as.numeric(stroke1$gender)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: NAs introduced by coercion\n```\n\n\n:::\n\n```{.r .cell-code}\nstroke1$ever_married[stroke1$ever_married == \"Yes\"] <- 1\nstroke1$ever_married[stroke1$ever_married == \"No\"] <- 2\nstroke1$ever_married <- as.numeric(stroke1$ever_married)\n\nstroke1$work_type[stroke1$work_type == \"Govt_job\"] <- 1\nstroke1$work_type[stroke1$work_type == \"Private\"] <- 2\nstroke1$work_type[stroke1$work_type == \"Self-employed\"] <- 3\nstroke1$work_type[stroke1$work_type == \"Never_worked\"] <- 4\nstroke1$work_type <- as.numeric(stroke1$work_type)\n\nstroke1$Residence_type[stroke1$Residence_type == \"Urban\"] <- 1\nstroke1$Residence_type[stroke1$Residence_type == \"Rural\"] <- 2\nstroke1$Residence_type <- as.numeric(stroke1$Residence_type)\n\nstroke1$avg_glucose_level <- as.numeric(stroke1$avg_glucose_level)\n\nstroke1$heart_disease <- as.numeric(stroke1$heart_disease)\n\nstroke1$hypertension <- as.numeric(stroke1$hypertension)\n\nstroke1$age <- round(as.numeric(stroke1$age), 2)\n\nstroke1$stroke <- as.numeric(stroke1$stroke)\n\nstroke1$smoking_status[stroke1$smoking_status == \"never smoked\"] <- 1\nstroke1$smoking_status[stroke1$smoking_status == \"formerly smoked\"] <- 2\nstroke1$smoking_status[stroke1$smoking_status == \"smokes\"] <- 3\nstroke1$smoking_status <- as.numeric(stroke1$smoking_status)\n\nstroke1 <- stroke1[, !(names(stroke1) %in% \"id\")]\nstroke1_clean <- na.omit(stroke1)\n```\n:::\n\n\n\nconverted all columns to numeric and removed id\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# converted all columns to numeric and removed id\nstr(stroke1_clean)\nnrow(stroke1_clean)\nLR_stroke1 <- stroke1_clean\nstr(LR_stroke1)\ncount_tables <- lapply(LR_stroke1, table)\ncount_tables\n```\n:::\n\n\n## 2. Apply Logistic Regression\n\nPart 2:Create and Run the Logistic Regression model from the  dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Part 2:Create and Run the Logistic Regression model from the  dataset\nmodel <- glm(stroke ~ gender + age + hypertension + heart_disease + ever_married + work_type + Residence_type + avg_glucose_level + bmi + smoking_status, data=LR_stroke1, family = binomial)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = stroke ~ gender + age + hypertension + heart_disease + \n    ever_married + work_type + Residence_type + avg_glucose_level + \n    bmi + smoking_status, family = binomial, data = LR_stroke1)\n\nCoefficients:\n                   Estimate Std. Error z value Pr(>|z|)    \n(Intercept)       -8.426854   0.873243  -9.650  < 2e-16 ***\ngender             0.080370   0.167274   0.480 0.630893    \nage                0.070967   0.006845  10.368  < 2e-16 ***\nhypertension       0.570797   0.182580   3.126 0.001770 ** \nheart_disease      0.417884   0.220311   1.897 0.057856 .  \never_married       0.174316   0.261832   0.666 0.505569    \nwork_type         -0.109615   0.126101  -0.869 0.384703    \nResidence_type     0.005932   0.162188   0.037 0.970822    \navg_glucose_level  0.004658   0.001375   3.388 0.000704 ***\nbmi                0.006275   0.012875   0.487 0.625954    \nsmoking_status     0.179921   0.106431   1.691 0.090932 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1403.5  on 3356  degrees of freedom\nResidual deviance: 1145.4  on 3346  degrees of freedom\nAIC: 1167.4\n\nNumber of Fisher Scoring iterations: 7\n```\n\n\n:::\n:::\n\n\n::: {.callout-important}\n## Issue - Unbalanced Data set\n\nThe dataset is oversampling stroke rate by 77%.\n\n:::\n\nIssue - Unbalanced Data set\n\nThe $stroke rate = 180/3357 = 054%$ . But the stroke rate in the US is 3.1% by the CDC, AHA, and the NCHS.\n\nThe dataset is oversampling stroke rate by 77%. We can either SMOTE, under/over sample....but too much time\n\nBest way is to recalibrate the intercept for this model (Ie change it here) so it can be used from now on\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Issue _ Unbalanced Data set #\n# The stroke rate = 180/3357 = 054%. But the stroke rate in the US is 3.1% by the CDC, AHA, and the NCHS. #\n# The dataset is oversampling stroke rate by 77%. We can either SMOTE, under/over sample....but too much time #\n# Best way is to recalibrate the intercept for this model (Ie change it here) so it can be used from now on #\nds_prev <- .054\npop_prev <- .031\nlog_odds_ds <- qlogis(ds_prev)\nlog_odds_pop <- qlogis(pop_prev)\noffset <- log_odds_pop - log_odds_ds\ncoefs <- coef(model)\ncoefs[1] <- coefs[1] + offset\nprint(coefs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      (Intercept)            gender               age      hypertension \n     -9.005873116       0.080369937       0.070967479       0.570796782 \n    heart_disease      ever_married         work_type    Residence_type \n      0.417883562       0.174315603      -0.109615162       0.005932360 \navg_glucose_level               bmi    smoking_status \n      0.004657820       0.006275415       0.179921439 \n```\n\n\n:::\n:::\n\n\nOriginal Intercept Coeff = -8.426854231 \n\nChanged intercept Coefficent to take into account current stroke rate or 3.1% = -9.005873116\n\nall the other intercepts remain the same\n\n## 3. Testing logistic Regression Model Assumptions\n\nPart 3: Testing logistic Regression Model Assumptions\n\nThere are several assumptions for Logistic Regression. They are:\n\n1. The Dependent Variable is binary (i.e, 0 or 1)\n2. There is a linear relationship between th logit of the outcome and each predictor\n3. There are NO high leverage outliers in the predictors\n4. There is No high multicollinearity (ie strong correlations) between predictors\n\nNow to test each assumption\n\n### 3.1 Testing Assumption 1\n\nTesting Assumption 1: The Dependent Variable is binary (0 or 1)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunique(LR_stroke1$stroke)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1 0\n```\n\n\n:::\n:::\n\n\n### 3.2 Testing Assumption 2\n\nTesting Assumption 2: There is a linear relationship between the outcome variable and each predictor\n\nfirst,  adjust all predictors so all values are positive\n\nConclusion: For all continuous variables , ageadj, avg_glucose_leveladj, and bniadj, the residual plots show linearity\n\nConclusion: all the other predictors are categorical, with the magenta line flat, and the values clustering around certain values, they are also appropriate for logistic regression\n\nConclusion for assumption 2 - Linearity is met\n\n\n::: {.cell}\n\n```{.r .cell-code}\nLR_stroke1$genderadj <- LR_stroke1$gender + abs(min(LR_stroke1$gender)) + 1\n\nLR_stroke1$ageadj <- LR_stroke1$age + abs(min(LR_stroke1$age)) + 1\n\nLR_stroke1$hypertensionadj <- LR_stroke1$hypertension + abs(min(LR_stroke1$hypertension)) + 1\n\nLR_stroke1$heart_diseaseadj <- LR_stroke1$heart_disease + abs(min(LR_stroke1$hypertension)) + 1\n\nLR_stroke1$ever_marriedadj <- LR_stroke1$ever_married + abs(min(LR_stroke1$ever_married)) + 1\n\nLR_stroke1$work_typeadj <- LR_stroke1$work_type + abs(min(LR_stroke1$work_type)) + 1\n\nLR_stroke1$Residence_typeadj <- LR_stroke1$Residence_type + abs(min(LR_stroke1$Residence_type)) + 1\n\nLR_stroke1$avg_glucose_leveladj <- LR_stroke1$avg_glucose_level + abs(min(LR_stroke1$avg_glucose_level)) + 1\n\nLR_stroke1$bmiadj <- LR_stroke1$bmi + abs(min(LR_stroke1$bmi)) + 1\n\nLR_stroke1$smoking_statusadj <- LR_stroke1$smoking_status + abs(min(LR_stroke1$smoking_status)) + 1\n\nstr(LR_stroke1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [3,357 × 21] (S3: tbl_df/tbl/data.frame)\n $ gender              : num [1:3357] 1 1 2 2 1 1 2 2 2 2 ...\n $ age                 : num [1:3357] 67 80 49 79 81 74 69 81 61 54 ...\n $ hypertension        : num [1:3357] 0 0 0 1 0 1 0 1 0 0 ...\n $ heart_disease       : num [1:3357] 1 1 0 0 0 1 0 0 1 0 ...\n $ ever_married        : num [1:3357] 1 1 1 1 1 1 2 1 1 1 ...\n $ work_type           : num [1:3357] 2 2 2 3 2 2 2 2 1 2 ...\n $ Residence_type      : num [1:3357] 1 2 1 2 1 2 1 2 2 1 ...\n $ avg_glucose_level   : num [1:3357] 229 106 171 174 186 ...\n $ bmi                 : num [1:3357] 36.6 32.5 34.4 24 29 27.4 22.8 29.7 36.8 27.3 ...\n $ smoking_status      : num [1:3357] 2 1 3 1 2 1 1 1 3 3 ...\n $ stroke              : num [1:3357] 1 1 1 1 1 1 1 1 1 1 ...\n $ genderadj           : num [1:3357] 3 3 4 4 3 3 4 4 4 4 ...\n $ ageadj              : num [1:3357] 81 94 63 93 95 88 83 95 75 68 ...\n $ hypertensionadj     : num [1:3357] 1 1 1 2 1 2 1 2 1 1 ...\n $ heart_diseaseadj    : num [1:3357] 2 2 1 1 1 2 1 1 2 1 ...\n $ ever_marriedadj     : num [1:3357] 3 3 3 3 3 3 4 3 3 3 ...\n $ work_typeadj        : num [1:3357] 4 4 4 5 4 4 4 4 3 4 ...\n $ Residence_typeadj   : num [1:3357] 3 4 3 4 3 4 3 4 4 3 ...\n $ avg_glucose_leveladj: num [1:3357] 285 162 227 230 242 ...\n $ bmiadj              : num [1:3357] 49.1 45 46.9 36.5 41.5 39.9 35.3 42.2 49.3 39.8 ...\n $ smoking_statusadj   : num [1:3357] 4 3 5 3 4 3 3 3 5 5 ...\n - attr(*, \"na.action\")= 'omit' Named int [1:1753] 2 9 10 14 20 24 28 30 32 39 ...\n  ..- attr(*, \"names\")= chr [1:1753] \"2\" \"9\" \"10\" \"14\" ...\n```\n\n\n:::\n\n```{.r .cell-code}\nStrokeAdj <- LR_stroke1\n\nStrokeAdj <- StrokeAdj[ , !(names(StrokeAdj) %in% c(\"gender\", \"age\", \"hypertension\", \"heart_disease\", \"ever_married\", \"work_type\", \"Residence_type\", \"avg_glucose_level\", \"bmi\", \"smoking_status\")) ]\n```\n:::\n\n\nFit the model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod.2 <- glm(stroke ~ genderadj + ageadj + hypertensionadj + heart_diseaseadj + ever_marriedadj + work_typeadj + Residence_typeadj + avg_glucose_leveladj + bmiadj + smoking_statusadj, data=StrokeAdj, family=binomial)\n# Plot Residuals\nresidualPlots(mod.2)\n```\n\n::: {.cell-output-display}\n![](Stroke_Results_1019_2025_latest_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](Stroke_Results_1019_2025_latest_files/figure-html/unnamed-chunk-10-2.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     Test stat Pr(>|Test stat|)  \ngenderadj               0.0000          1.00000  \nageadj                  2.0626          0.15095  \nhypertensionadj         0.0000          1.00000  \nheart_diseaseadj        0.0000          1.00000  \never_marriedadj         0.0000          1.00000  \nwork_typeadj            3.1406          0.07636 .\nResidence_typeadj       0.0000          1.00000  \navg_glucose_leveladj    0.0103          0.91921  \nbmiadj                  0.3947          0.52983  \nsmoking_statusadj       0.4775          0.48953  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n### 3.3 Testing Assumption 3\n\nTesting Assumption 3: assess influential outliers using car package and influencePlot\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalias(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModel :\nstroke ~ gender + age + hypertension + heart_disease + ever_married + \n    work_type + Residence_type + avg_glucose_level + bmi + smoking_status\n```\n\n\n:::\n\n```{.r .cell-code}\n# install.packages(\"Hmisc\")\n# library(Hmisc)\nrcorr(as.matrix(LR_stroke1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     gender   age hypertension heart_disease ever_married\ngender                 1.00 -0.06        -0.04         -0.10         0.03\nage                   -0.06  1.00         0.26          0.26        -0.49\nhypertension          -0.04  0.26         1.00          0.11        -0.11\nheart_disease         -0.10  0.26         0.11          1.00        -0.07\never_married           0.03 -0.49        -0.11         -0.07         1.00\nwork_type              0.01  0.14         0.05          0.03        -0.02\nResidence_type        -0.01 -0.02         0.00         -0.01         0.01\navg_glucose_level     -0.07  0.24         0.17          0.14        -0.12\nbmi                   -0.02  0.04         0.13          0.00        -0.13\nsmoking_status        -0.08  0.03        -0.01          0.06        -0.06\nstroke                -0.01  0.24         0.14          0.14        -0.07\ngenderadj              1.00 -0.06        -0.04         -0.10         0.03\nageadj                -0.06  1.00         0.26          0.26        -0.49\nhypertensionadj       -0.04  0.26         1.00          0.11        -0.11\nheart_diseaseadj      -0.10  0.26         0.11          1.00        -0.07\never_marriedadj        0.03 -0.49        -0.11         -0.07         1.00\nwork_typeadj           0.01  0.14         0.05          0.03        -0.02\nResidence_typeadj     -0.01 -0.02         0.00         -0.01         0.01\navg_glucose_leveladj  -0.07  0.24         0.17          0.14        -0.12\nbmiadj                -0.02  0.04         0.13          0.00        -0.13\nsmoking_statusadj     -0.08  0.03        -0.01          0.06        -0.06\n                     work_type Residence_type avg_glucose_level   bmi\ngender                    0.01          -0.01             -0.07 -0.02\nage                       0.14          -0.02              0.24  0.04\nhypertension              0.05           0.00              0.17  0.13\nheart_disease             0.03          -0.01              0.14  0.00\never_married             -0.02           0.01             -0.12 -0.13\nwork_type                 1.00          -0.01              0.03 -0.02\nResidence_type           -0.01           1.00              0.01  0.01\navg_glucose_level         0.03           0.01              1.00  0.16\nbmi                      -0.02           0.01              0.16  1.00\nsmoking_status           -0.02          -0.04              0.01  0.03\nstroke                    0.04          -0.01              0.14  0.01\ngenderadj                 0.01          -0.01             -0.07 -0.02\nageadj                    0.14          -0.02              0.24  0.04\nhypertensionadj           0.05           0.00              0.17  0.13\nheart_diseaseadj          0.03          -0.01              0.14  0.00\never_marriedadj          -0.02           0.01             -0.12 -0.13\nwork_typeadj              1.00          -0.01              0.03 -0.02\nResidence_typeadj        -0.01           1.00              0.01  0.01\navg_glucose_leveladj      0.03           0.01              1.00  0.16\nbmiadj                   -0.02           0.01              0.16  1.00\nsmoking_statusadj        -0.02          -0.04              0.01  0.03\n                     smoking_status stroke genderadj ageadj hypertensionadj\ngender                        -0.08  -0.01      1.00  -0.06           -0.04\nage                            0.03   0.24     -0.06   1.00            0.26\nhypertension                  -0.01   0.14     -0.04   0.26            1.00\nheart_disease                  0.06   0.14     -0.10   0.26            0.11\never_married                  -0.06  -0.07      0.03  -0.49           -0.11\nwork_type                     -0.02   0.04      0.01   0.14            0.05\nResidence_type                -0.04  -0.01     -0.01  -0.02            0.00\navg_glucose_level              0.01   0.14     -0.07   0.24            0.17\nbmi                            0.03   0.01     -0.02   0.04            0.13\nsmoking_status                 1.00   0.02     -0.08   0.03           -0.01\nstroke                         0.02   1.00     -0.01   0.24            0.14\ngenderadj                     -0.08  -0.01      1.00  -0.06           -0.04\nageadj                         0.03   0.24     -0.06   1.00            0.26\nhypertensionadj               -0.01   0.14     -0.04   0.26            1.00\nheart_diseaseadj               0.06   0.14     -0.10   0.26            0.11\never_marriedadj               -0.06  -0.07      0.03  -0.49           -0.11\nwork_typeadj                  -0.02   0.04      0.01   0.14            0.05\nResidence_typeadj             -0.04  -0.01     -0.01  -0.02            0.00\navg_glucose_leveladj           0.01   0.14     -0.07   0.24            0.17\nbmiadj                         0.03   0.01     -0.02   0.04            0.13\nsmoking_statusadj              1.00   0.02     -0.08   0.03           -0.01\n                     heart_diseaseadj ever_marriedadj work_typeadj\ngender                          -0.10            0.03         0.01\nage                              0.26           -0.49         0.14\nhypertension                     0.11           -0.11         0.05\nheart_disease                    1.00           -0.07         0.03\never_married                    -0.07            1.00        -0.02\nwork_type                        0.03           -0.02         1.00\nResidence_type                  -0.01            0.01        -0.01\navg_glucose_level                0.14           -0.12         0.03\nbmi                              0.00           -0.13        -0.02\nsmoking_status                   0.06           -0.06        -0.02\nstroke                           0.14           -0.07         0.04\ngenderadj                       -0.10            0.03         0.01\nageadj                           0.26           -0.49         0.14\nhypertensionadj                  0.11           -0.11         0.05\nheart_diseaseadj                 1.00           -0.07         0.03\never_marriedadj                 -0.07            1.00        -0.02\nwork_typeadj                     0.03           -0.02         1.00\nResidence_typeadj               -0.01            0.01        -0.01\navg_glucose_leveladj             0.14           -0.12         0.03\nbmiadj                           0.00           -0.13        -0.02\nsmoking_statusadj                0.06           -0.06        -0.02\n                     Residence_typeadj avg_glucose_leveladj bmiadj\ngender                           -0.01                -0.07  -0.02\nage                              -0.02                 0.24   0.04\nhypertension                      0.00                 0.17   0.13\nheart_disease                    -0.01                 0.14   0.00\never_married                      0.01                -0.12  -0.13\nwork_type                        -0.01                 0.03  -0.02\nResidence_type                    1.00                 0.01   0.01\navg_glucose_level                 0.01                 1.00   0.16\nbmi                               0.01                 0.16   1.00\nsmoking_status                   -0.04                 0.01   0.03\nstroke                           -0.01                 0.14   0.01\ngenderadj                        -0.01                -0.07  -0.02\nageadj                           -0.02                 0.24   0.04\nhypertensionadj                   0.00                 0.17   0.13\nheart_diseaseadj                 -0.01                 0.14   0.00\never_marriedadj                   0.01                -0.12  -0.13\nwork_typeadj                     -0.01                 0.03  -0.02\nResidence_typeadj                 1.00                 0.01   0.01\navg_glucose_leveladj              0.01                 1.00   0.16\nbmiadj                            0.01                 0.16   1.00\nsmoking_statusadj                -0.04                 0.01   0.03\n                     smoking_statusadj\ngender                           -0.08\nage                               0.03\nhypertension                     -0.01\nheart_disease                     0.06\never_married                     -0.06\nwork_type                        -0.02\nResidence_type                   -0.04\navg_glucose_level                 0.01\nbmi                               0.03\nsmoking_status                    1.00\nstroke                            0.02\ngenderadj                        -0.08\nageadj                            0.03\nhypertensionadj                  -0.01\nheart_diseaseadj                  0.06\never_marriedadj                  -0.06\nwork_typeadj                     -0.02\nResidence_typeadj                -0.04\navg_glucose_leveladj              0.01\nbmiadj                            0.03\nsmoking_statusadj                 1.00\n\nn= 3357 \n\n\nP\n                     gender age    hypertension heart_disease ever_married\ngender                      0.0012 0.0204       0.0000        0.1140      \nage                  0.0012        0.0000       0.0000        0.0000      \nhypertension         0.0204 0.0000              0.0000        0.0000      \nheart_disease        0.0000 0.0000 0.0000                     0.0000      \never_married         0.1140 0.0000 0.0000       0.0000                    \nwork_type            0.3863 0.0000 0.0051       0.0862        0.2313      \nResidence_type       0.5077 0.3076 0.8569       0.5527        0.5150      \navg_glucose_level    0.0000 0.0000 0.0000       0.0000        0.0000      \nbmi                  0.2487 0.0144 0.0000       0.8185        0.0000      \nsmoking_status       0.0000 0.0448 0.7537       0.0005        0.0009      \nstroke               0.4296 0.0000 0.0000       0.0000        0.0002      \ngenderadj            0.0000 0.0012 0.0204       0.0000        0.1140      \nageadj               0.0012 0.0000 0.0000       0.0000        0.0000      \nhypertensionadj      0.0204 0.0000 0.0000       0.0000        0.0000      \nheart_diseaseadj     0.0000 0.0000 0.0000       0.0000        0.0000      \never_marriedadj      0.1140 0.0000 0.0000       0.0000        0.0000      \nwork_typeadj         0.3863 0.0000 0.0051       0.0862        0.2313      \nResidence_typeadj    0.5077 0.3076 0.8569       0.5527        0.5150      \navg_glucose_leveladj 0.0000 0.0000 0.0000       0.0000        0.0000      \nbmiadj               0.2487 0.0144 0.0000       0.8185        0.0000      \nsmoking_statusadj    0.0000 0.0448 0.7537       0.0005        0.0009      \n                     work_type Residence_type avg_glucose_level bmi   \ngender               0.3863    0.5077         0.0000            0.2487\nage                  0.0000    0.3076         0.0000            0.0144\nhypertension         0.0051    0.8569         0.0000            0.0000\nheart_disease        0.0862    0.5527         0.0000            0.8185\never_married         0.2313    0.5150         0.0000            0.0000\nwork_type                      0.6768         0.0467            0.3243\nResidence_type       0.6768                   0.6427            0.5689\navg_glucose_level    0.0467    0.6427                           0.0000\nbmi                  0.3243    0.5689         0.0000                  \nsmoking_status       0.3764    0.0208         0.7679            0.0925\nstroke               0.0259    0.7171         0.0000            0.6866\ngenderadj            0.3863    0.5077         0.0000            0.2487\nageadj               0.0000    0.3076         0.0000            0.0144\nhypertensionadj      0.0051    0.8569         0.0000            0.0000\nheart_diseaseadj     0.0862    0.5527         0.0000            0.8185\never_marriedadj      0.2313    0.5150         0.0000            0.0000\nwork_typeadj         0.0000    0.6768         0.0467            0.3243\nResidence_typeadj    0.6768    0.0000         0.6427            0.5689\navg_glucose_leveladj 0.0467    0.6427         0.0000            0.0000\nbmiadj               0.3243    0.5689         0.0000            0.0000\nsmoking_statusadj    0.3764    0.0208         0.7679            0.0925\n                     smoking_status stroke genderadj ageadj hypertensionadj\ngender               0.0000         0.4296 0.0000    0.0012 0.0204         \nage                  0.0448         0.0000 0.0012    0.0000 0.0000         \nhypertension         0.7537         0.0000 0.0204    0.0000 0.0000         \nheart_disease        0.0005         0.0000 0.0000    0.0000 0.0000         \never_married         0.0009         0.0002 0.1140    0.0000 0.0000         \nwork_type            0.3764         0.0259 0.3863    0.0000 0.0051         \nResidence_type       0.0208         0.7171 0.5077    0.3076 0.8569         \navg_glucose_level    0.7679         0.0000 0.0000    0.0000 0.0000         \nbmi                  0.0925         0.6866 0.2487    0.0144 0.0000         \nsmoking_status                      0.2559 0.0000    0.0448 0.7537         \nstroke               0.2559                0.4296    0.0000 0.0000         \ngenderadj            0.0000         0.4296           0.0012 0.0204         \nageadj               0.0448         0.0000 0.0012           0.0000         \nhypertensionadj      0.7537         0.0000 0.0204    0.0000                \nheart_diseaseadj     0.0005         0.0000 0.0000    0.0000 0.0000         \never_marriedadj      0.0009         0.0002 0.1140    0.0000 0.0000         \nwork_typeadj         0.3764         0.0259 0.3863    0.0000 0.0051         \nResidence_typeadj    0.0208         0.7171 0.5077    0.3076 0.8569         \navg_glucose_leveladj 0.7679         0.0000 0.0000    0.0000 0.0000         \nbmiadj               0.0925         0.6866 0.2487    0.0144 0.0000         \nsmoking_statusadj    0.0000         0.2559 0.0000    0.0448 0.7537         \n                     heart_diseaseadj ever_marriedadj work_typeadj\ngender               0.0000           0.1140          0.3863      \nage                  0.0000           0.0000          0.0000      \nhypertension         0.0000           0.0000          0.0051      \nheart_disease        0.0000           0.0000          0.0862      \never_married         0.0000           0.0000          0.2313      \nwork_type            0.0862           0.2313          0.0000      \nResidence_type       0.5527           0.5150          0.6768      \navg_glucose_level    0.0000           0.0000          0.0467      \nbmi                  0.8185           0.0000          0.3243      \nsmoking_status       0.0005           0.0009          0.3764      \nstroke               0.0000           0.0002          0.0259      \ngenderadj            0.0000           0.1140          0.3863      \nageadj               0.0000           0.0000          0.0000      \nhypertensionadj      0.0000           0.0000          0.0051      \nheart_diseaseadj                      0.0000          0.0862      \never_marriedadj      0.0000                           0.2313      \nwork_typeadj         0.0862           0.2313                      \nResidence_typeadj    0.5527           0.5150          0.6768      \navg_glucose_leveladj 0.0000           0.0000          0.0467      \nbmiadj               0.8185           0.0000          0.3243      \nsmoking_statusadj    0.0005           0.0009          0.3764      \n                     Residence_typeadj avg_glucose_leveladj bmiadj\ngender               0.5077            0.0000               0.2487\nage                  0.3076            0.0000               0.0144\nhypertension         0.8569            0.0000               0.0000\nheart_disease        0.5527            0.0000               0.8185\never_married         0.5150            0.0000               0.0000\nwork_type            0.6768            0.0467               0.3243\nResidence_type       0.0000            0.6427               0.5689\navg_glucose_level    0.6427            0.0000               0.0000\nbmi                  0.5689            0.0000               0.0000\nsmoking_status       0.0208            0.7679               0.0925\nstroke               0.7171            0.0000               0.6866\ngenderadj            0.5077            0.0000               0.2487\nageadj               0.3076            0.0000               0.0144\nhypertensionadj      0.8569            0.0000               0.0000\nheart_diseaseadj     0.5527            0.0000               0.8185\never_marriedadj      0.5150            0.0000               0.0000\nwork_typeadj         0.6768            0.0467               0.3243\nResidence_typeadj                      0.6427               0.5689\navg_glucose_leveladj 0.6427                                 0.0000\nbmiadj               0.5689            0.0000                     \nsmoking_statusadj    0.0208            0.7679               0.0925\n                     smoking_statusadj\ngender               0.0000           \nage                  0.0448           \nhypertension         0.7537           \nheart_disease        0.0005           \never_married         0.0009           \nwork_type            0.3764           \nResidence_type       0.0208           \navg_glucose_level    0.7679           \nbmi                  0.0925           \nsmoking_status       0.0000           \nstroke               0.2559           \ngenderadj            0.0000           \nageadj               0.0448           \nhypertensionadj      0.7537           \nheart_diseaseadj     0.0005           \never_marriedadj      0.0009           \nwork_typeadj         0.3764           \nResidence_typeadj    0.0208           \navg_glucose_leveladj 0.7679           \nbmiadj               0.0925           \nsmoking_statusadj                     \n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# install.packages(\"car\")\n# library(car)\ninfluencePlot(model)\n```\n\n::: {.cell-output-display}\n![](Stroke_Results_1019_2025_latest_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        StudRes          Hat       CookD\n83    2.6917353 0.0039267816 0.012237368\n84    1.5018344 0.0343771041 0.006641860\n87    3.0732709 0.0012042796 0.011476828\n131   3.1608870 0.0006013465 0.007697762\n152   3.1135601 0.0005613972 0.006237531\n2583 -0.8509399 0.0399302730 0.001668526\n```\n\n\n:::\n:::\n\n\nCooks D ranges from 0 to .0122 \n\nWhile the ideal size is 4/N (4/3357 = 0.012), its far outside the danger zone of .5\n\nConclusion: Assumption 3 is met - No substantial outliers\n\n### 3.4 Testing Assumption 4\n\nTesting Assumption 4 : Multicollinearity using vif in the care package\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvif(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           gender               age      hypertension     heart_disease \n         1.041499          1.213552          1.051213          1.083661 \n     ever_married         work_type    Residence_type avg_glucose_level \n         1.018892          1.051698          1.006965          1.105268 \n              bmi    smoking_status \n         1.117138          1.049260 \n```\n\n\n:::\n:::\n\n\nConclusion. All vif values are below  5 or 10. Ideally most values should be around 1. Range for all\n\nthe predictors is between: 1.01 - 1.21. Way below the danger threshold of 5 to 10. \n\nConclusion: No Multicollinearity\n\nFinal Conclusion: All4 assumptions are met, logistic regression is a valid model\n\n\n## 4 Analysis of the Model\n\nPart 4: Analysis of the Model\n\nThere are 2 issues with the model. Fit and Predictive Capability\n\n### 4.1 Use Hosmer-lemesho and Naglekerke R\n\nPart 1  fit. Use Hosmer-lemesho and Naglekerke R for non technical audience\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# install.packages(\"ResourceSelection\")\n# library(ResourceSelection)\nhoslem.test(model$y, fitted(model), g = 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tHosmer and Lemeshow goodness of fit (GOF) test\n\ndata:  model$y, fitted(model)\nX-squared = 5.2704, df = 8, p-value = 0.7283\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# install.packages(\"rcompanion\")\n# library(rcompanion)\nnagelkerke(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Models\n                                                                                                                                                                               \nModel: \"glm, stroke ~ gender + age + hypertension + heart_disease + ever_married + work_type + Residence_type + avg_glucose_level + bmi + smoking_status, binomial, LR_stroke1\"\nNull:  \"glm, stroke ~ 1, binomial, LR_stroke1\"                                                                                                                                 \n\n$Pseudo.R.squared.for.model.vs.null\n                             Pseudo.R.squared\nMcFadden                            0.1838790\nCox and Snell (ML)                  0.0739944\nNagelkerke (Cragg and Uhler)        0.2165560\n\n$Likelihood.ratio.test\n Df.diff LogLik.diff  Chisq    p.value\n     -10     -129.03 258.07 1.0892e-49\n\n$Number.of.observations\n           \nModel: 3357\nNull:  3357\n\n$Messages\n[1] \"Note: For models fit with REML, these statistics are based on refitting with ML\"\n\n$Warnings\n[1] \"None\"\n```\n\n\n:::\n:::\n\n\n### 4.2 Predictive Capability\n\nPart 2 - Predictive Capability\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# install.packages(\"pROC\")\n# library(pROC)\nprobs <- predict(model, type = \"response\")\nroc_obj <- roc(LR_stroke1$stroke, probs)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nSetting levels: control = 0, case = 1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nSetting direction: controls < cases\n```\n\n\n:::\n\n```{.r .cell-code}\nauc(roc_obj)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nArea under the curve: 0.8285\n```\n\n\n:::\n:::\n\n\nPredict AUC cross validation\n\n::: {.callout-note}\n## Need to implement AUC cross validation\n\nCould not understand yet how to implement the AUC cross validation\n\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Predict AUC cross validation\n# install.packages(\"cvAUC\")\n# library(cvAUC)\n```\n:::\n\n\n\nConfusion Matrix\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Confusion Matrix\nLR_stroke1$gender <- factor(LR_stroke1$gender)\nLR_stroke1$hypertension <- factor(LR_stroke1$hypertension)\nLR_stroke1$heart_disease <- factor(LR_stroke1$heart_disease)\nLR_stroke1$ever_married <- factor(LR_stroke1$ever_married)\nLR_stroke1$work_type <- factor(LR_stroke1$work_type)\nLR_stroke1$Residence_type <- factor(LR_stroke1$Residence_type)\nLR_stroke1$smoking_status <- factor(LR_stroke1$smoking_status)\nLR_stroke1$stroke <- factor(LR_stroke1$stroke)\n```\n:::\n\n\nfit logistic regression model\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# fit logistic regression model\nmodel_CM <- glm(stroke ~ gender + age + hypertension + heart_disease + ever_married + work_type + Residence_type + avg_glucose_level + bmi + smoking_status, data=LR_stroke1, family = binomial)\n```\n:::\n\n\nGet Predicted Probabilities for each observation\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get Predicted Probabilities for each observation\npred_prob <- predict(model_CM, type = \"response\")\n```\n:::\n\n\ncreate 10 confusion matrices at threshold intervals between 1 and 0 to create a ROC\n\nClassify prediction using a threshold (0.5 is common but can adjust)\n\nIF 1 row is all 0's then model doesn't show any predictability\n\n**At threshold of around 1.0**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create 10 confusion matrices at threshold intervals between 1 and 0 to create a ROC\n# Classify prediction using a threshold (0.5 is common but can adjust)\n# IF 1 row is all 0's then model doesn't show any predictability\n# At threshold of around 1.0\npred_class <- factor(ifelse(pred_prob > .99, 1, 0), levels = c(0, 1))\nconf_matrix <- confusionMatrix(pred_class, factor(LR_stroke1$stroke, levels = c(\"0\", \"1\")), positive = \"1\")\nprint(conf_matrix$table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Reference\nPrediction    0    1\n         0 3177  180\n         1    0    0\n```\n\n\n:::\n:::\n\n\nIF 1 row is all 0's then model doesn't show any predictability\n\n**At threshold of 0.9**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# At threshold of 0.9\npred_class <- factor(ifelse(pred_prob > 0.9, 1, 0), levels = c(0, 1))\nconf_matrix <- confusionMatrix(pred_class, factor(LR_stroke1$stroke, levels = c(\"0\", \"1\")), positive = \"1\")\nprint(conf_matrix$table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Reference\nPrediction    0    1\n         0 3177  180\n         1    0    0\n```\n\n\n:::\n:::\n\n\nIF 1 row is all 0's then model doesn't show any predictability\n\n**At threshold of 0.8**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# At threshold of 0.8\npred_class <- factor(ifelse(pred_prob > 0.8, 1, 0), levels = c(0, 1))\nconf_matrix <- confusionMatrix(pred_class, factor(LR_stroke1$stroke, levels = c(\"0\", \"1\")), positive = \"1\")\nprint(conf_matrix$table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Reference\nPrediction    0    1\n         0 3177  180\n         1    0    0\n```\n\n\n:::\n:::\n\n\nIF 1 row is all 0's then model doesn't show any predictability\n\n**At threshold of 0.7**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# At threshold of 0.7\npred_class <- factor(ifelse(pred_prob > 0.7, 1, 0), levels = c(0, 1))\nconf_matrix <- confusionMatrix(pred_class, factor(LR_stroke1$stroke, levels = c(\"0\", \"1\")), positive = \"1\")\nprint(conf_matrix$table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Reference\nPrediction    0    1\n         0 3177  180\n         1    0    0\n```\n\n\n:::\n:::\n\n\n**At threshold of 0.6**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# At threshold of 0.6\npred_class <- factor(ifelse(pred_prob > 0.6, 1, 0), levels = c(0, 1))\nconf_matrix <- confusionMatrix(pred_class, factor(LR_stroke1$stroke, levels = c(\"0\", \"1\")), positive = \"1\")\nprint(conf_matrix$table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Reference\nPrediction    0    1\n         0 3177  179\n         1    0    1\n```\n\n\n:::\n:::\n\n\nat threshold of 0.6 that starts the models predictability\n\nExtract precision,Recall and F1 from confusion matrix using the caret package\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract precision, Recall and F1 from confusion matrix using the caret package\nprecision <- conf_matrix$byClass[\"Pos Pred Value\"] \nrecall <- conf_matrix$byClass[\"Sensitivity\"]\nf1 <- 2 * ((precision * recall)/ (precision + recall))\nprint(sprintf(\"F1: %f\", f1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"F1: 0.011050\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(sprintf(\"recall: %f\", recall))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"recall: 0.005556\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(sprintf(\"precision: %f\", precision))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"precision: 1.000000\"\n```\n\n\n:::\n:::\n\n\n**at threshold of 0.5**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# at threshold of 0.5\npred_class <- factor(ifelse(pred_prob > 0.5, 1, 0), levels = c(0, 1))\nconf_matrix <- confusionMatrix(pred_class, factor(LR_stroke1$stroke, levels = c(\"0\", \"1\")), positive = \"1\")\nprint(conf_matrix$table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Reference\nPrediction    0    1\n         0 3176  179\n         1    1    1\n```\n\n\n:::\n:::\n\n\nExtract precision,Recall and F1 from confusion matrix using the caret package\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract precision,Recall and F1 from confusion matrix using the caret package\nprecision <- conf_matrix$byClass[\"Pos Pred Value\"] \nrecall <- conf_matrix$byClass[\"Sensitivity\"]\nf1 <- 2 * ((precision * recall)/ (precision + recall))\nprint(sprintf(\"F1: %f\", f1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"F1: 0.010989\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(sprintf(\"recall: %f\", recall))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"recall: 0.005556\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(sprintf(\"precision: %f\", precision))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"precision: 0.500000\"\n```\n\n\n:::\n:::\n\n\n**At threshold of 0.4**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# At threshold of 0.4\npred_class <- factor(ifelse(pred_prob > 0.4, 1, 0), levels = c(0, 1))\nconf_matrix <- confusionMatrix(pred_class, factor(LR_stroke1$stroke, levels = c(\"0\", \"1\")), positive = \"1\")\nprint(conf_matrix$table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Reference\nPrediction    0    1\n         0 3171  174\n         1    6    6\n```\n\n\n:::\n:::\n\n\nExtract precision,Recall and F1 from confusion matrix using the caret package\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract precision,Recall and F1 from confusion matrix using the caret package\nprecision <- conf_matrix$byClass[\"Pos Pred Value\"] \nrecall <- conf_matrix$byClass[\"Sensitivity\"]\nf1 <- 2 * ((precision * recall)/ (precision + recall))\nprint(sprintf(\"F1: %f\", f1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"F1: 0.062500\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(sprintf(\"recall: %f\", recall))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"recall: 0.033333\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(sprintf(\"precision: %f\", precision))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"precision: 0.500000\"\n```\n\n\n:::\n:::\n\n\n**at threshold of 0.3**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# at threshold of 0.3\npred_class <- factor(ifelse(pred_prob > 0.3, 1, 0), levels = c(0, 1))\nconf_matrix <- confusionMatrix(pred_class, factor(LR_stroke1$stroke, levels = c(\"0\", \"1\")), positive = \"1\")\nprint(conf_matrix$table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Reference\nPrediction    0    1\n         0 3140  164\n         1   37   16\n```\n\n\n:::\n:::\n\n\nExtract precision,Recall and F1 from confusion matrix using the caret package\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract precision,Recall and F1 from confusion matrix using the caret package\nprecision <- conf_matrix$byClass[\"Pos Pred Value\"] \nrecall <- conf_matrix$byClass[\"Sensitivity\"]\nf1 <- 2 * ((precision * recall)/ (precision + recall))\nprint(sprintf(\"F1: %f\", f1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"F1: 0.137339\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(sprintf(\"recall: %f\", recall))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"recall: 0.088889\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(sprintf(\"precision: %f\", precision))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"precision: 0.301887\"\n```\n\n\n:::\n:::\n\n\n**at threshold of 0.2**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# at threshold of 0.2\npred_class <- factor(ifelse(pred_prob > 0.2, 1, 0), levels = c(0, 1))\nconf_matrix <- confusionMatrix(pred_class, factor(LR_stroke1$stroke, levels = c(\"0\", \"1\")), positive = \"1\")\nprint(conf_matrix$table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Reference\nPrediction    0    1\n         0 3040  134\n         1  137   46\n```\n\n\n:::\n:::\n\n\nExtract precision,Recall and F1 from confusion matrix using the caret package\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract precision,Recall and F1 from confusion matrix using the caret package\nprecision <- conf_matrix$byClass[\"Pos Pred Value\"] \nrecall <- conf_matrix$byClass[\"Sensitivity\"]\nf1 <- 2 * ((precision * recall)/ (precision + recall))\nprint(sprintf(\"F1: %f\", f1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"F1: 0.253444\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(sprintf(\"recall: %f\", recall))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"recall: 0.255556\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(sprintf(\"precision: %f\", precision))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"precision: 0.251366\"\n```\n\n\n:::\n:::\n\n\n\nUsing the different Confusion Matrices, Create the ROC curve\n\n\n\n\n\n\n\n## Original Code\n\nBelow we see the Original Code shared by Steve: **Stroke_Results_1019_2025_latest_440PM_SW_For_Group.R**\n\n```{{r}}\ninstall.packages(\"dplyr\")\ninstall.packages(\"car\")\ninstall.packages(\"ResourceSelection\")\ninstall.packages(\"caret\")\ninstall.packages(\"car\")\nlibrary(dplyr)\nlibrary(car)\nlibrary(ResourceSelection)\nlibrary(caret)\nlibrary(car)\nstroke1 <- read.csv(\"D:\\\\stroke.csv\")\nhead(stroke1)\nnrow(stroke1)\nsummary(stroke1)\ncount_tables <- lapply(stroke1, table)\ncount_tables\n#-------------------------------------------Part 1:  preparing the data---------------------------------#\n# Smoking Status - remove unknown#\n#bmi - remove N/A#\n# Work type - remove children#\n# age create numerical variable with 2 places after the decimal#\n#gender -remove other#\nstroke1[stroke1 == \"N/A\"] <- NA\nstroke1[stroke1 == \"Unknown\"] <- NA\nstroke1[stroke1 == \"children\"] <- NA\nstroke1[stroke1 == \"other\"] <- NA\nstroke1$bmi <- round(as.numeric(stroke1$bmi), 2)\nstroke1$gender[stroke1$gender == \"Male\"] <- 1\nstroke1$gender[stroke1$gender == \"Female\"] <- 2\nstroke1$gender <- as.numeric(stroke1$gender)\nstroke1$ever_married[stroke1$ever_married == \"Yes\"] <- 1\nstroke1$ever_married[stroke1$ever_married == \"No\"] <- 2\nstroke1$ever_married <- as.numeric(stroke1$ever_married)\nstroke1$work_type[stroke1$work_type == \"Govt_job\"] <- 1\nstroke1$work_type[stroke1$work_type == \"Private\"] <- 2\nstroke1$work_type[stroke1$work_type == \"Self-employed\"] <- 3\nstroke1$work_type[stroke1$work_type == \"Never_worked\"] <- 4\nstroke1$work_type <- as.numeric(stroke1$work_type)\nstroke1$Residence_type[stroke1$Residence_type == \"Urban\"] <- 1\nstroke1$Residence_type[stroke1$Residence_type == \"Rural\"] <- 2\nstroke1$Residence_type <- as.numeric(stroke1$Residence_type)\nstroke1$avg_glucose_level <- as.numeric(stroke1$avg_glucose_level)\nstroke1$heart_disease <- as.numeric(stroke1$heart_disease)\nstroke1$hypertension <- as.numeric(stroke1$hypertension)\nstroke1$age <- round(as.numeric(stroke1$age), 2)\nstroke1$stroke <- as.numeric(stroke1$stroke)\nstroke1$smoking_status[stroke1$smoking_status == \"never smoked\"] <- 1\nstroke1$smoking_status[stroke1$smoking_status == \"formerly smoked\"] <- 2\nstroke1$smoking_status[stroke1$smoking_status == \"smokes\"] <- 3\nstroke1$smoking_status <- as.numeric(stroke1$smoking_status)\nstroke1 <- stroke1[, !(names(stroke1) %in% \"id\")]\nstroke1_clean <- na.omit(stroke1)\n#converted all columns to numeric and removed id#\nstr(stroke1_clean)\nnrow(stroke1_clean)\nLR_stroke1 <- stroke1_clean\nstr(LR_stroke1)\ncount_tables <- lapply(LR_stroke1, table)\ncount_tables\n#-------------------------Part 2:Create and Run the Logistic Regression model from the  dataset-------------#\nmodel <- glm(stroke ~ gender + age + hypertension + heart_disease + ever_married + work_type + Residence_type + avg_glucose_level + bmi + smoking_status, data=LR_stroke1, family = binomial)\nsummary(model)\n# ----------------------------------------------Issue _ Unbalanced Data set--------------------------------------#\n# The stroke rate = 180/3357 = 054%. But the stroke rate in the US is 3.1% by the CDC, AHA, and the NCHS.--------#\n# The dataset is oversampling stroke rate by 77%. We can either SMOTE, under/over sample....but too much time----#\n# Best way is to recalibrate the intercept for this model (Ie change it here) so it can be used from now on------#\nds_prev <- .054\npop_prev <- .031\nlog_odds_ds <- qlogis(ds_prev)\nlog_odds_pop <- qlogis(pop_prev)\noffset <- log_odds_pop - log_odds_ds\ncoefs <- coef(model)\ncoefs[1] <- coefs[1] + offset\nprint(coefs)\n# Original Intercept Coeff = -8.426854231#\n# Changed intercept Coefficent to take into account current stroke rate or 3.1% = -9.005873116-------------------#\n# all the other intercepts remain the same-----------------------------------------------------------------------#\n# ----------------------------------Part 3: Testing logistic Regression Model Assumptions------------------------#\n# There are several assumptions for Logistic Regression#\n# They are:#\n#(1) The Dependent Variable is binary (i.e, 0 or 1)#\n#(2) There is a linear relationship between th logit of the outcome and each predictor#\n#(3) There are NO high leverage outliers in the predictors#\n#(4) There is No high multicollinearity (ie strong correlations) between predictors#\n####################################:Now to test each assumption: ################\n# Testing Assumption 1: The Dependent Variable is binary (0 or 1)#\nunique(LR_stroke1$stroke)\n#Testing Assumption 2: There is a linear relationship between the outcome variable and each predictor\n#first,  adjust all predictors so all values are positive#\n# Conclusion: For all continuous variables , ageadj, avg_glucose_leveladj, and bniadj, the residual plots show linearity#\n# Conclusion:all the other predictors are categorical, with the magenta line flat, and the values clustering around certain values, they are also appropriate for logistic regression#\n# ---------------------------------------Conclusion for assumption 2 - Linearity is met--------------------------------#\n# Testing Assumption 3: assess influential outliers using car package and influencePlot#\nalias(model)\ninstall.packages(\"Hmisc\")\nlibrary(Hmisc)\nrcorr(as.matrix(LR_stroke1))\ninstall.packages(\"car\")\nlibrary(car)\ninfluencePlot(model)\n# Cooks D ranges from 0 to .0122 While the ideal size is 4/N (4/3357 = 0.012), its far outside the danger zone of .5\n#--------------------------------- Conclusion: Assumption 3 is met - No substantial outliers---------------------#\n# Testing Assumption 4 : Multicollinearity using vif in the care package#\nvif(model)\n#--------------------Conclusion. All vif values are below  5 or 10. Ideally most values should be around 1. Range for all#\n# the predictors is between: 1.01 - 1.21. Way below the danger threshold of 5 to 10. Conclusion: No Multicollinearity####\n#####################################################################################################################\n# -----------------Final Conclusion: All4 assumptions are met, logistic regression is a valid model---------------#\n####################################################################################################################\n# ---------------------------------------------Part 4: Analysis of the Model----------------------------------------#\n# -----------------------There are 2 issues with the model. Fit and Predictive Capability---------------------------#\n# ----------------Part 1  fit. Use Hosmer-lemesho and Naglekerke R for non technical audience-----------------------#\ninstall.packages(\"ResourceSelection\")\nlibrary(ResourceSelection)\nhoslem.test(model$y, fitted(model), g = 10)\ninstall.packages(\"rcompanion\")\nlibrary(rcompanion)\nnagelkerke(model)\n# -----------------------Part 2 - Predictive Capability-----------------------------------------------------------\ninstall.packages(\"pROC\")\nlibrary(pROC)\nprobs <- predict(model, type = \"response\")\nroc_obj <- roc(LR_stroke1$stroke, probs)\nauc(roc_obj)\n# Predict AUC cross validation\ninstall.packages(\"cvAUC\")\nlibrary(cvAUC)\n# Confusion Matrix\nLR_stroke1$gender <- factor(LR_stroke1$gender)\nLR_stroke1$hypertension <- factor(LR_stroke1$hypertension)\nLR_stroke1$heart_disease <- factor(LR_stroke1$heart_disease)\nLR_stroke1$ever_married <- factor(LR_stroke1$ever_married)\nLR_stroke1$work_type <- factor(LR_stroke1$work_type)\nLR_stroke1$Residence_type <- factor(LR_stroke1$Residence_type)\nLR_stroke1$smoking_status <- factor(LR_stroke1$smoking_status)\nLR_stroke1$stroke <- factor(LR_stroke1$stroke)\n# fit logistic regression model\nmodel_CM <- glm(stroke ~ gender + age + hypertension + heart_disease + ever_married + work_type + Residence_type + avg_glucose_level + bmi + smoking_status, data=LR_stroke1, family = binomial)\n# Get Predicted Probabilities for each observation\npred_prob <- predict(model_CM, type = \"response\")\ninstall.packages(\"caret\")\nlibrary(caret)\n# create 10 confusion matrices at threshold intervals between 1 and 0 to create a ROC\n#Classify prediction using a threshold (0.5 is common but can adjust)\n#---------------------------IF 1 row is all 0's then model doesn't show any predictability-------------------#\n# At threshold of around 1.0 #\npred_class <- factor(ifelse(pred_prob > .99, 1, 0), levels = c(0, 1))\nconf_matrix <- confusionMatrix(pred_class, factor(LR_stroke1$stroke, levels = c(\"0\", \"1\")), positive = \"1\")\nprint(conf_matrix$table)\n#-------------------------IF 1 row is all 0's then model doesn't show any predictability-----------------------#\n# At threshold of 0.9 #\npred_class <- factor(ifelse(pred_prob > 0.9, 1, 0), levels = c(0, 1))\nconf_matrix <- confusionMatrix(pred_class, factor(LR_stroke1$stroke, levels = c(\"0\", \"1\")), positive = \"1\")\nprint(conf_matrix$table)\n#-----------------------IF 1 row is all 0's then model doesn't show any predictability--------------------------#\n# At threshold of 0.8#\npred_class <- factor(ifelse(pred_prob > 0.8, 1, 0), levels = c(0, 1))\nconf_matrix <- confusionMatrix(pred_class, factor(LR_stroke1$stroke, levels = c(\"0\", \"1\")), positive = \"1\")\nprint(conf_matrix$table)\n#----------------------IF 1 row is all 0's then model doesn't show any predictability---------------------------#\n# At threshold of 0.7#\npred_class <- factor(ifelse(pred_prob > 0.7, 1, 0), levels = c(0, 1))\nconf_matrix <- confusionMatrix(pred_class, factor(LR_stroke1$stroke, levels = c(\"0\", \"1\")), positive = \"1\")\nprint(conf_matrix$table)\n# At threshold of 0.6#\npred_class <- factor(ifelse(pred_prob > 0.6, 1, 0), levels = c(0, 1))\nconf_matrix <- confusionMatrix(pred_class, factor(LR_stroke1$stroke, levels = c(\"0\", \"1\")), positive = \"1\")\nprint(conf_matrix$table)\n################################################################################################################\n#-----------------------------at threshold of 0.6 that starts the models predictability------------------------#\n################################################################################################################\n# Extract precision,Recall and F1 from confusion matrix using the caret package #\nprecision <- conf_matrix$byClass[\"Pos Pred Value\"] \nrecall <- conf_matrix$byClass[\"Sensitivity\"]\nf1 <- 2 * ((precision * recall)/ (precision + recall))\nprint(f1)\nprint(recall)\nprint(precision)\n# at threshold of 0.5#\npred_class <- factor(ifelse(pred_prob > 0.5, 1, 0), levels = c(0, 1))\nconf_matrix <- confusionMatrix(pred_class, factor(LR_stroke1$stroke, levels = c(\"0\", \"1\")), positive = \"1\")\nprint(conf_matrix$table)\n# Extract precision,Recall and F1 from confusion matrix using the caret package #\nprecision <- conf_matrix$byClass[\"Pos Pred Value\"] \nrecall <- conf_matrix$byClass[\"Sensitivity\"]\nf1 <- 2 * ((precision * recall)/ (precision + recall))\nprint(f1)\nprint(recall)\nprint(precision)\n# At threshold of 0.4#\npred_class <- factor(ifelse(pred_prob > 0.4, 1, 0), levels = c(0, 1))\nconf_matrix <- confusionMatrix(pred_class, factor(LR_stroke1$stroke, levels = c(\"0\", \"1\")), positive = \"1\")\nprint(conf_matrix$table)\n# Extract precision,Recall and F1 from confusion matrix using the caret package #\nprecision <- conf_matrix$byClass[\"Pos Pred Value\"] \nrecall <- conf_matrix$byClass[\"Sensitivity\"]\nf1 <- 2 * ((precision * recall)/ (precision + recall))\nprint(f1)\nprint(recall)\nprint(precision)\n# at threshold of 0.3#\npred_class <- factor(ifelse(pred_prob > 0.3, 1, 0), levels = c(0, 1))\nconf_matrix <- confusionMatrix(pred_class, factor(LR_stroke1$stroke, levels = c(\"0\", \"1\")), positive = \"1\")\nprint(conf_matrix$table)\n# Extract precision,Recall and F1 from confusion matrix using the caret package #\nprecision <- conf_matrix$byClass[\"Pos Pred Value\"] \nrecall <- conf_matrix$byClass[\"Sensitivity\"]\nf1 <- 2 * ((precision * recall)/ (precision + recall))\nprint(f1)\nprint(recall)\nprint(precision)\n# at threshold of 0.2#\npred_class <- factor(ifelse(pred_prob > 0.2, 1, 0), levels = c(0, 1))\nconf_matrix <- confusionMatrix(pred_class, factor(LR_stroke1$stroke, levels = c(\"0\", \"1\")), positive = \"1\")\nprint(conf_matrix$table)\n# Extract precision,Recall and F1 from confusion matrix using the caret package #\nprecision <- conf_matrix$byClass[\"Pos Pred Value\"] \nrecall <- conf_matrix$byClass[\"Sensitivity\"]\nf1 <- 2 * ((precision * recall)/ (precision + recall))\nprint(f1)\nprint(recall)\nprint(precision)\n# At Threshold of 0.18#\npred_class <- factor(ifelse(pred_prob > 0.18, 1, 0), levels = c(0, 1))\nconf_matrix <- confusionMatrix(pred_class, factor(LR_stroke1$stroke, levels = c(\"0\", \"1\")), positive = \"1\")\nprint(conf_matrix$table)\n# Extract precision,Recall and F1 from confusion matrix using the caret package #\nprecision <- conf_matrix$byClass[\"Pos Pred Value\"] \nrecall <- conf_matrix$Class[\"Sensitivity\"]\nf1 <- 2 * ((precision * recall)/ (precision + recall))\nprint(f1)\nprint(recall)\nprint(precision)\n# At threshold of 0.15#\npred_class <- factor(ifelse(pred_prob > 0.15, 1, 0), levels = c(0, 1))\nconf_matrix <- confusionMatrix(pred_class, factor(LR_stroke1$stroke, levels = c(\"0\", \"1\")), positive = \"1\")\nprint(conf_matrix$table)\n# Extract precision,Recall and F1 from confusion matrix using the caret package #\nprecision <- conf_matrix$byClass[\"Pos Pred Value\"] \nrecall <- conf_matrix$byClass[\"Sensitivity\"]\nf1 <- 2 * ((precision * recall)/ (precision + recall))\nprint(f1)\nprint(recall)\nprint(precision)\n# at threshold of 0.1#\npred_class <- factor(ifelse(pred_prob > 0.1, 1, 0), levels = c(0, 1))\nconf_matrix <- confusionMatrix(pred_class, factor(LR_stroke1$stroke, levels = c(\"0\", \"1\")), positive = \"1\")\nprint(conf_matrix$table)\n# Extract precision,Recall and F1 from confusion matrix using the caret package #\nprecision <- conf_matrix$byClass[\"Pos Pred Value\"] \nrecall <- conf_matrix$byClass[\"Sensitivity\"]\nf1 <- 2 * ((precision * recall)/ (precision + recall))\nprint(f1)\nprint(recall)\nprint(precision)\n# at threshold of 0.05#\npred_class <- factor(ifelse(pred_prob > 0.05, 1, 0), levels = c(0, 1))\nconf_matrix <- confusionMatrix(pred_class, factor(LR_stroke1$stroke, levels = c(\"0\", \"1\")), positive = \"1\")\nprint(conf_matrix$table)\n# Extract precision,Recall and F1 from confusion matrix using the caret package #\nprecision <- conf_matrix$byClass[\"Pos Pred Value\"] \nrecall <- conf_matrix$byClass[\"Sensitivity\"]\nf1 <- 2 * ((precision * recall)/ (precision + recall))\nprint(f1)\nprint(recall)\nprint(precision)\n# Using the different Confusion Matrices, Create the ROC curve\n```\n\n### References\n\n::: {#refs}\n:::",
    "supporting": [
      "Stroke_Results_1019_2025_latest_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}